//! Compiled rows of the Product Operation Registry.
//!
//! One row per product operation reachable over a host boundary. Rows are
//! sorted by id and kept one per line so that a new command has exactly one
//! insertion point and a review diff shows exactly one row.
//! `#[rustfmt::skip]` keeps that layout; `operations_are_sorted_and_unique`
//! in `mod.rs` verifies lookup coverage; a const assertion also rejects invalid builds.
//!
//! Columns: id, remote workspace stance, peer stance, CLI peer host support.
//! Desktop peer host support is derived (see `OperationDefinition::host_support`).
//!
//! Adding a Tauri command: register it in `src/apps/desktop/src/lib.rs`, then add
//! one `op(...)` row here with a real stance for every column. `Unaudited` is a
//! frozen backlog and may not be used for new rows (see `baseline.rs`).

use super::{
    HostSupport, OperationDefinition, OperationSurface, PeerStance, RemoteWorkspaceStance,
};
use PeerStance::{ControllerLocal, HostControlPlane, OperatorOnly, Proxied};
use RemoteWorkspaceStance::{Agnostic, LocalOnly, Routed, Unaudited, Unsupported};

const fn op(
    id: &'static str,
    remote_workspace: RemoteWorkspaceStance,
    peer: PeerStance,
    cli_peer: HostSupport,
) -> OperationDefinition {
    OperationDefinition {
        id,
        surface: OperationSurface::TauriCommand,
        remote_workspace,
        peer,
        cli_peer,
    }
}

/// A HostInvoke name that is not a registered Tauri command: CLI peer host
/// aliases kept for older controllers, and the detached-dispatch target verbs.
const fn host_invoke_only(
    id: &'static str,
    remote_workspace: RemoteWorkspaceStance,
    peer: PeerStance,
    cli_peer: HostSupport,
) -> OperationDefinition {
    OperationDefinition {
        id,
        surface: OperationSurface::HostInvokeOnly,
        remote_workspace,
        peer,
        cli_peer,
    }
}

const HANDLED: HostSupport = HostSupport::Handled;
/// Cell used by every `ControllerLocal` / `OperatorOnly` row: the verdict refuses
/// the command before host dispatch, so per-host support is not consulted.
pub(super) const REFUSED: HostSupport = HostSupport::Unsupported {
    reason: "the controller keeps this command; peer hosts refuse it before dispatch",
};
pub(super) const CLI_NOT_IMPLEMENTED: HostSupport = HostSupport::Unsupported {
    reason: "the CLI peer host has no handler for this command",
};
pub(super) const CLI_NO_DESKTOP_IDE_SURFACE: HostSupport = HostSupport::Unsupported {
    reason: "the CLI peer host does not run this desktop IDE surface",
};
pub(super) const CLI_NO_BROWSER_OR_OS_AUTOMATION: HostSupport = HostSupport::Unsupported {
    reason: "the CLI peer host has no browser or OS automation runtime",
};
pub(super) const CLI_NO_REMOTE_WORKSPACE_UI: HostSupport = HostSupport::Unsupported {
    reason: "the CLI peer host does not expose the remote-workspace UI surface",
};
pub(super) const SOFT_EMPTY_NO_CRON_HOST: HostSupport = HostSupport::SoftEmpty {
    reason: "the CLI peer host has no cron host; readiness is acknowledged so hydrate succeeds",
};
pub(super) const SOFT_EMPTY_MINIAPPS: HostSupport = HostSupport::SoftEmpty {
    reason: "MiniApps are a desktop-hosted runtime; the CLI peer host reports an empty catalog so hydrate succeeds",
};
pub(super) const SOFT_EMPTY_ACP_CLIENTS: HostSupport = HostSupport::SoftEmpty {
    reason: "ACP client management is a desktop settings surface; the CLI peer host reports none",
};
pub(super) const SOFT_EMPTY_BACKGROUND_COMMANDS: HostSupport = HostSupport::SoftEmpty {
    reason: "background command activities are desktop-hosted; the CLI peer host reports none",
};

#[rustfmt::skip]
pub(super) const OPERATIONS: &[OperationDefinition] = &[
    op("accept_file",                                                Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("accept_operation",                                           Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("accept_session",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("account_connect_devices",                                    Agnostic,    ControllerLocal,  REFUSED),
    op("account_delete_device",                                      Agnostic,    ControllerLocal,  REFUSED),
    op("account_device_rpc",                                         Agnostic,    ControllerLocal,  REFUSED),
    op("account_execute_on_device",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("account_get_credential_hint",                                Agnostic,    ControllerLocal,  REFUSED),
    op("account_github_info",                                        Agnostic,    ControllerLocal,  REFUSED),
    op("account_github_poll",                                        Agnostic,    ControllerLocal,  REFUSED),
    op("account_github_start",                                       Agnostic,    ControllerLocal,  REFUSED),
    op("account_list_devices",                                       Agnostic,    ControllerLocal,  REFUSED),
    op("account_load_older_session",                                 Agnostic,    ControllerLocal,  REFUSED),
    op("account_login",                                              Agnostic,    ControllerLocal,  REFUSED),
    op("account_logout",                                             Agnostic,    ControllerLocal,  REFUSED),
    op("account_online_devices",                                     Agnostic,    ControllerLocal,  REFUSED),
    op("account_relay_capabilities",                                Agnostic,    ControllerLocal,  REFUSED),
    op("account_status",                                             Agnostic,    ControllerLocal,  REFUSED),
    op("account_subscribe_session",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("account_token_expired",                                      Agnostic,    ControllerLocal,  REFUSED),
    op("account_unsubscribe_session",                                Agnostic,    ControllerLocal,  REFUSED),
    op("account_update_device_alias",                                Agnostic,    ControllerLocal,  REFUSED),
    op("acknowledge_external_ecosystems_command",                    Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("activate_session_goal",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("add_skill",                                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("appearance_market_browse",                                   Agnostic,    ControllerLocal,  REFUSED),
    op("appearance_market_download_release",                         LocalOnly,   ControllerLocal,  REFUSED),
    op("appearance_market_get_listing",                              Agnostic,    ControllerLocal,  REFUSED),
    op("appearance_market_get_review_submission",                    Agnostic,    ControllerLocal,  REFUSED),
    op("appearance_market_list_review_submissions",                  Agnostic,    ControllerLocal,  REFUSED),
    op("appearance_market_list_submissions",                         Agnostic,    ControllerLocal,  REFUSED),
    op("appearance_market_review_submission",                        Agnostic,    ControllerLocal,  REFUSED),
    op("appearance_market_submit_package",                           LocalOnly,   ControllerLocal,  REFUSED),
    op("appearance_market_withdraw_submission",                      Agnostic,    ControllerLocal,  REFUSED),
    op("append_flow_chat_diagnostics",                               LocalOnly,   ControllerLocal,  REFUSED),
    op("apply_external_hook_import_command",                         Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("apply_external_mcp_import_command",                          Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("apply_external_source_control_action_command",               Unsupported, Proxied,          HANDLED),
    op("apply_patch",                                                Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("archive_all_sessions",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("archive_session",                                            Unaudited,   Proxied,          HANDLED),
    op("browser_control_disconnect",                                 LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("browser_control_enable_default_cdp",                         LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("browser_control_get_status",                                 LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("browser_control_launch",                                     LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("browser_control_list_browsers",                              LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("browser_control_restart_with_cdp",                           LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("browser_get_url",                                            LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("browser_webview_capture_preview",                            LocalOnly,   ControllerLocal,  REFUSED),
    op("browser_webview_create",                                     LocalOnly,   ControllerLocal,  REFUSED),
    op("browser_webview_eval",                                       LocalOnly,   ControllerLocal,  REFUSED),
    op("browser_webview_navigate",                                   LocalOnly,   ControllerLocal,  REFUSED),
    op("browser_webview_reload",                                     LocalOnly,   ControllerLocal,  REFUSED),
    op("browser_webview_set_agent_target_state",                     LocalOnly,   ControllerLocal,  REFUSED),
    op("browser_webview_set_bounds",                                 LocalOnly,   ControllerLocal,  REFUSED),
    op("btw_ask_stream",                                             Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("btw_cancel",                                                 Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("cancel_acp_dialog_turn",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("cancel_dialog_turn",                                         Agnostic,    Proxied,          HANDLED),
    op("cancel_insights_generation",                                 LocalOnly,   ControllerLocal,  REFUSED),
    op("cancel_mcp_remote_oauth",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("cancel_search",                                              Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("cancel_session",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("cancel_subscription_login",                                  LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("cancel_tool",                                                Agnostic,    Proxied,          HANDLED),
    op("cancel_transfer",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("canonicalize_agent_profile_configs",                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("check_command_exists",                                       LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("check_commands_exist",                                       LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("check_for_updates",                                          Agnostic,    ControllerLocal,  REFUSED),
    op("check_git_isolation",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("check_path_exists",                                          Routed,      Proxied,          HANDLED),
    op("choose_external_mcp_conflict_command",                       Unsupported, Proxied,          HANDLED),
    op("choose_external_subagent_conflict_command",                  Unsupported, Proxied,          HANDLED),
    op("cleanup_invalid_workspaces",                                 Unaudited,   Proxied,          HANDLED),
    op("clear_mcp_remote_auth",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("clear_project_permission_grants",                            Agnostic,    Proxied,          HANDLED),
    op("clear_session_thread_goal",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("clear_web_search_credential",                                Agnostic,    Proxied,          HANDLED),
    op("close_workspace",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("compact_session",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("compress_path",                                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("compute_diff",                                               Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("computer_use_control_preview",                               LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("computer_use_control_status",                                LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("computer_use_control_stop",                                  LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("computer_use_get_status",                                    LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("computer_use_open_system_settings",                          LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("computer_use_request_permissions",                           LocalOnly,   Proxied,          CLI_NO_BROWSER_OR_OS_AUTOMATION),
    op("confirm_frontend_update",                                    LocalOnly,   ControllerLocal,  REFUSED),
    op("control_background_command",                                 Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("control_deep_review_queue",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("create_acp_flow_session",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("create_assistant_workspace",                                 Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("create_control_conversation",                                Agnostic,    Proxied,          HANDLED),
    op("create_cron_job",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("create_custom_agent",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("create_directory",                                           Routed,      Proxied,          HANDLED),
    op("create_file",                                                Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("create_miniapp",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("create_session",                                             Unaudited,   Proxied,          HANDLED),
    op("create_subagent",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("debug_close_devtools",                                       LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("debug_devtools_available",                                   LocalOnly,   ControllerLocal,  REFUSED),
    op("debug_element_picked",                                       LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("debug_open_devtools",                                        LocalOnly,   ControllerLocal,  REFUSED),
    op("decompress_path",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_agent_companion_pet_package",                         Unaudited,   ControllerLocal,  REFUSED),
    op("delete_all_archived_sessions",                               Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_assistant_workspace",                                 Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_cron_job",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_custom_agent",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_directory",                                           Routed,      Proxied,          HANDLED),
    op("delete_file",                                                Routed,      Proxied,          HANDLED),
    op("delete_mcp_server",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_miniapp",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_persisted_session",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_session",                                             Unaudited,   Proxied,          HANDLED),
    op("delete_skill",                                               Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("delete_subagent",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("dismiss_announcement",                                       Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_answer",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_append",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_cancel",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_continue",                                          Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_install_cli_cancel",                                Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_install_cli_poll",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_install_cli_start",                                 Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_list_jobs",                                         Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_list_targets",                                      Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_load_transcript",                                   Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_probe_target",                                      Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_provision_target",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_query",                                             Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_save_transcript",                                   Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_status",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_submit",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_sync_model_config",                                 Agnostic,    ControllerLocal,  REFUSED),
    op("dispatch_sync_result",                                       Agnostic,    ControllerLocal,  REFUSED),
    host_invoke_only("dispatch_target_answer",                       Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_append",                       Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_cancel",                       Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_continue",                     Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_list",                         Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_probe",                        Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_query",                        Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_status",                       Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_submit",                       Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_workspace_bundle_begin",       Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_workspace_bundle_chunk",       Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_workspace_bundle_commit",      Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_workspace_provision",          Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_workspace_sync",               Agnostic,    HostControlPlane, HANDLED),
    host_invoke_only("dispatch_target_workspace_sync_chunk",         Agnostic,    HostControlPlane, HANDLED),
    op("download_skill_market",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("download_update",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("editor_ai_cancel",                                           Unaudited,   Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("editor_ai_stream",                                           Unaudited,   Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ensure_assistant_bootstrap",                                 Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("ensure_control_conversation", Agnostic, Proxied, HANDLED),
    op("ensure_coordinator_session",                                 Routed,      Proxied,          HANDLED),
    op("execute_tool",                                               Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("expand_external_prompt_command_command",                     Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("explorer_get_children",                                      Routed,      Proxied,          CLI_NO_REMOTE_WORKSPACE_UI),
    op("explorer_get_children_paginated",                            Routed,      Proxied,          CLI_NO_REMOTE_WORKSPACE_UI),
    op("explorer_get_file_tree",                                     Routed,      Proxied,          CLI_NO_REMOTE_WORKSPACE_UI),
    op("export_config",                                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("export_diagnostics_bundle",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("export_local_file_to_path",                                  Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("export_session_transcript",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("fetch_mcp_app_resource",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("fork_session",                                               Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("frontend_update_candidate_failed",                           LocalOnly,   ControllerLocal,  REFUSED),
    op("frontend_update_candidate_ready",                            LocalOnly,   ControllerLocal,  REFUSED),
    op("generate_commit_message",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("generate_insights",                                          Routed,      ControllerLocal,  REFUSED),
    op("generate_session_title",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_acp_clients",                                            Unaudited,   Proxied,          SOFT_EMPTY_ACP_CLIENTS),
    op("get_acp_session_commands",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_acp_session_options",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_agent_profile_config",                                   Unaudited,   Proxied,          HANDLED),
    op("get_agent_profile_configs",                                  Unaudited,   Proxied,          HANDLED),
    op("get_ai_model_catalog",                                       Agnostic,    Proxied,          HANDLED),
    op("get_all_modified_files",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_all_tools_info",                                         Unaudited,   Proxied,          HANDLED),
    op("get_announcement_tips",                                      Agnostic,    ControllerLocal,  REFUSED),
    op("get_app_state",                                              Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_app_version",                                            Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_assistant_workspaces",                                   Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_available_modes",                                        Unaudited,   Proxied,          HANDLED),
    op("get_available_tools",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_baseline_snapshot_diff",                                 Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_chat_mcp_catalog",                                       Unsupported, Proxied,          HANDLED),
    op("get_clipboard_files",                                        LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_clipboard_image",                                        LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_config",                                                 Unaudited,   Proxied,          HANDLED),
    op("get_configs",                                                Unaudited,   Proxied,          HANDLED),
    op("get_current_workspace",                                      Agnostic,    Proxied,          HANDLED),
    op("get_custom_agent_detail",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_default_review_team_definition",                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_directory_children",                                     Routed,      Proxied,          HANDLED),
    op("get_directory_children_paginated",                           Routed,      Proxied,          HANDLED),
    op("get_external_ecosystem_awareness_command",                   Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_external_hook_catalog",                                  Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_external_hook_import_snapshot",                          Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_external_source_control_snapshot",                       Unsupported, Proxied,          HANDLED),
    op("get_external_source_discovery_snapshot",                     Unsupported, Proxied,          HANDLED),
    op("get_external_source_snapshot",                               Unsupported, Proxied,          HANDLED),
    op("get_file_change_history",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_file_diff",                                              Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_file_editor_sync_hash",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_file_metadata",                                          Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_file_tree",                                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_frontend_update_status",                                 LocalOnly,   ControllerLocal,  REFUSED),
    op("get_global_config_health",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_global_config_status",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_global_skill_settings",                                  Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_health_status",                                          Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_instruction_source_catalog",                             Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_latest_insights",                                        LocalOnly,   ControllerLocal,  REFUSED),
    // This machine's own models.dev projections for the Model Settings surface a
    // controller renders while a peer is selected. The data belongs to the
    // public models.dev catalog, which every host refreshes for itself, so the
    // controller keeps this read local instead of pulling the peer's copy.
    op("get_local_models_dev_catalogs",                              LocalOnly,   ControllerLocal,  REFUSED),
    op("get_mcp_prompt",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_mcp_remote_oauth_session",                               Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_mcp_server_status",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_mcp_servers",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_mcp_tool_ui_uri",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_memory_paths",                                           Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_miniapp",                                                Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_miniapp_draft_storage",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_miniapp_storage",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_miniapp_versions",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_mode_skill_configs",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_model_configs",                                          Unaudited,   Proxied,          HANDLED),
    op("get_models_dev_catalog_status",                              LocalOnly,   Proxied,          HANDLED),
    op("get_native_prompt_command_conflicts_command",                Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_opened_workspaces",                                      Agnostic,    Proxied,          HANDLED),
    op("get_operation_diff",                                         Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_operation_summary",                                      Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_pending_announcements",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("get_pending_update",                                         Agnostic,    ControllerLocal,  REFUSED),
    op("get_prevent_sleep_enabled",                                  LocalOnly,   ControllerLocal,  REFUSED),
    op("get_primary_assistant_workspace",                            Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_project_permission_rules",                               Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_readonly_tools_info",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_recent_workspaces",                                      Agnostic,    Proxied,          HANDLED),
    op("get_runtime_capabilities",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_runtime_logging_info",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_session_file_diff_stats",                                Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_session_files",                                          Unaudited,   Proxied,          HANDLED),
    op("get_session_interaction_mailbox",                         Agnostic,    Proxied,          HANDLED),
    op("get_session_lineage",                                        Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_session_operations",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_session_permission_mode",                                Routed,      Proxied,          HANDLED),
    op("get_session_stats",                                          Unaudited,   Proxied,          HANDLED),
    op("get_session_thread_goal",                                    Unaudited,   Proxied,          HANDLED),
    op("get_session_turns",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_session_usage_report",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_skill_configs",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_snapshot_sessions",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_snapshot_system_stats",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_startup_native_trace",                                   Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_statistics",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_subagent_detail",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_subscription_login_status",                              LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_system_info",                                            Agnostic,    Proxied,          HANDLED),
    op("get_token_usage_statistics",                                 Agnostic,    Proxied,          HANDLED),
    op("get_tool_info",                                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_turn_files",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_watched_paths",                                          LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("get_web_search_credential_status",                           Agnostic,    Proxied,          HANDLED),
    host_invoke_only("get_workspace_info",                           Agnostic,    Proxied,          HANDLED),
    op("get_workspace_reference_snapshot",                           Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_add_files",                                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_add_worktree",                                           Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_checkout_branch",                                        Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_cherry_pick",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_cherry_pick_abort",                                      Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_cherry_pick_continue",                                   Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_commit",                                                 Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_create_branch",                                          Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_delete_branch",                                          Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_branches",                                           Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_changed_files",                                      Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_commits",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_diff",                                               Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_enhanced_branches",                                  Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_file_content",                                       Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_graph",                                              Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_repository",                                         Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_repository_basic",                                   Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_get_repository_trust",                                   Routed,      Proxied,          HANDLED),
    op("git_get_status",                                             Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_is_repository",                                          Routed,      Proxied,          HANDLED),
    op("git_list_worktrees",                                         Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_pull",                                                   Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_push",                                                   Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_remove_worktree",                                        Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_reset_files",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_reset_to_commit",                                        Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_resolve_revision",                                       Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("git_trust_repository",                                       Routed,      OperatorOnly,     REFUSED),
    op("grant_miniapp_path",                                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("grant_miniapp_workspace",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("has_insights_data",                                          Routed,      ControllerLocal,  REFUSED),
    op("hide_agent_companion_desktop_pet",                           LocalOnly,   ControllerLocal,  REFUSED),
    op("hide_main_window_after_close_request",                       LocalOnly,   ControllerLocal,  REFUSED),
    op("html_preview_create",                                        Routed,      ControllerLocal,  REFUSED),
    op("html_preview_release",                                       Agnostic,    ControllerLocal,  REFUSED),
    op("i18n_get_config",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("i18n_get_current_language",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("i18n_get_supported_languages",                               Agnostic,    ControllerLocal,  REFUSED),
    op("i18n_set_config",                                            Agnostic,    ControllerLocal,  REFUSED),
    op("i18n_set_language",                                          Agnostic,    ControllerLocal,  REFUSED),
    op("import_agent_companion_pet_package",                         Unaudited,   ControllerLocal,  REFUSED),
    op("import_config",                                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("initialize_acp_clients",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("initialize_ai",                                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("initialize_mcp_servers",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("initialize_mcp_servers_non_destructive",                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("initialize_tray_after_startup",                              LocalOnly,   ControllerLocal,  REFUSED),
    op("initialize_workspace_startup_state",                         Routed,      Proxied,          HANDLED),
    op("install_acp_client_cli",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("install_pending_update",                                     Agnostic,    ControllerLocal,  REFUSED),
    op("install_update",                                             Agnostic,    ControllerLocal,  REFUSED),
    op("interrupt_dialog_turn",                                      LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_agent_companion_pets",                                  Unaudited,   ControllerLocal,  REFUSED),
    op("list_agent_tool_names",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_ai_models_by_config",                                   Unaudited,   Proxied,          HANDLED),
    op("list_archived_sessions",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_background_command_activities",                         Unaudited,   Proxied,          SOFT_EMPTY_BACKGROUND_COMMANDS),
    op("list_cron_jobs",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_directory_files",                                       Routed,      Proxied,          HANDLED),
    host_invoke_only("list_files",                                   Routed,      Proxied,          HANDLED),
    op("list_manageable_subagents",                                  Routed,      Proxied,          HANDLED),
    op("list_mcp_prompts",                                           Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_mcp_resources",                                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_miniapps",                                              Unaudited,   Proxied,          SOFT_EMPTY_MINIAPPS),
    op("list_pending_permission_requests",                           Agnostic,    Proxied,          HANDLED),
    op("list_persisted_sessions",                                    Unaudited,   Proxied,          HANDLED),
    host_invoke_only("list_persisted_sessions_count",                Agnostic,    Proxied,          HANDLED),
    op("list_persisted_sessions_page",                               Unaudited,   Proxied,          HANDLED),
    op("list_project_permission_audit",                              Agnostic,    Proxied,          HANDLED),
    op("list_project_permission_grants",                             Agnostic,    Proxied,          HANDLED),
    op("list_sessions",                                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_skill_market",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_subagents",                                             Routed,      Proxied,          HANDLED),
    op("list_subscription_accounts",                                 LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("list_visible_subagents",                                     Routed,      Proxied,          HANDLED),
    op("load_acp_json_config",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("load_canvas_artifact",                                       Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("load_canvas_state",                                          Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("load_git_repo_history",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("load_insights_report",                                       LocalOnly,   ControllerLocal,  REFUSED),
    op("load_mcp_json_config",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("load_persisted_session_metadata",                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("load_session_event_backfill",                                Agnostic,    Proxied,          HANDLED),
    op("load_session_turn_window",                                   Routed,      Proxied,          HANDLED),
    op("load_session_turns",                                         Unaudited,   Proxied,          HANDLED),
    op("local_file_download",                                       Agnostic,    ControllerLocal,  REFUSED),
    op("logout_subscription_account",                                LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("manage_dialog_queue",                                      Routed,      Proxied,          HANDLED),
    op("mark_announcement_seen",                                     Agnostic,    ControllerLocal,  REFUSED),
    op("mark_openbitfun_control_surface_ready",                          Agnostic,    ControllerLocal,  REFUSED),
    op("mark_openbitfun_control_surface_unready",                        Agnostic,    ControllerLocal,  REFUSED),
    op("market_image_load",                                         Agnostic,    ControllerLocal,  REFUSED),
    op("miniapp_agent_cancel",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_agent_cancel_stale_runs",                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_agent_ensure_session",                               LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_agent_run",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_agent_turn_text",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_ai_cancel",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_ai_chat",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_ai_complete",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_ai_list_models",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_apply_draft",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_create_draft",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_decline_builtin_update",                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_dialog_message",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_discard_draft",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_draft_host_call",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_draft_worker_call",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_draft_worker_stop",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_get_customization_metadata",                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_get_draft",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_host_call",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_import_from_path",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_install_deps",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_browse",                                      Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_capture_window",                              LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_get_listing",                                 Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_import_package",                              LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_inspect_package",                             LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_install",                                     LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_installed_origins",                           LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_installed_status",                            LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_list_submissions",                            Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_set_favorite",                                Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_set_rating",                                  Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_submit_installed",                            LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_market_withdraw_submission",                         Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_permission_diff_for_draft",                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_recompile",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_render_slide_page",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_runtime_status",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_set_draft_permissions",                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_sync_draft_from_fs",                                 Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_sync_from_fs",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_worker_call",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("miniapp_worker_list_running",                                Unaudited,   Proxied,          SOFT_EMPTY_MINIAPPS),
    op("miniapp_worker_stop",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("minimize_to_tray",                                           LocalOnly,   ControllerLocal,  REFUSED),
    op("mutate_external_hook_import_command",                        Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("never_show_announcement",                                    Agnostic,    ControllerLocal,  REFUSED),
    op("notify_cron_host_ready",                                     Unaudited,   Proxied,          SOFT_EMPTY_NO_CRON_HOST),
    op("open_html_file_in_browser",                                  LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("open_remote_workspace",                                      Routed,      Proxied,          HANDLED),
    op("open_workspace",                                             Routed,      Proxied,          HANDLED),
    op("page_create_open_link",                                      Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_delete",                                                Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_delete_version",                                        Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_deploy",                                                Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_list",                                                  Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_list_versions",                                         Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_publish",                                               LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_save_version",                                          LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_unpublish",                                             Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("page_update",                                                Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("paste_files",                                                Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("peer_control_attach",                                        Agnostic,    HostControlPlane, HANDLED),
    op("peer_control_detach",                                        Agnostic,    HostControlPlane, HANDLED),
    op("peer_controller_set_active",                                 Agnostic,    ControllerLocal,  REFUSED),
    op("peer_host_invoke_complete",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("peer_mode_ping",                                             Agnostic,    HostControlPlane, HANDLED),
    op("plan_external_hook_import_command",                          Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("plan_external_mcp_import_command",                           Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("predownload_acp_client_adapter",                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("preview_commit_message",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("probe_acp_client_requirements",                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("product_control_invoke",                                     Agnostic,    Proxied,          HANDLED),
    op("project_ai_model_reasoning_catalog",                         Agnostic,    Proxied,          HANDLED),
    op("quick_commit_message",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("quit_app",                                                   LocalOnly,   ControllerLocal,  REFUSED),
    op("read_background_command_output",                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("read_file_content",                                          Routed,      Proxied,          HANDLED),
    op("read_mcp_resource",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("record_voice_exchange", Agnostic, Proxied, HANDLED),
    op("recover_interrupted_dialog_turn",                            LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("refresh_model_client",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("refresh_models_dev_catalog_now",                             LocalOnly,   Proxied,          HANDLED),
    op("refresh_subscription_account",                               LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reject_file",                                                Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reject_operation",                                           Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reload_config",                                              Unaudited,   Proxied,          HANDLED),
    op("reload_custom_agents",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reload_session_context",                                     Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("reload_subagents",                                           Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_close_workspace",                                     Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_connect_configure_bot",                               Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_get_bot_verbose_mode",                        Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_get_device_info",                             Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_get_form_state",                              Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_get_lan_ip",                                  Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_get_lan_network_info",                        Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_get_methods",                                 Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_set_bot_verbose_mode",                        Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_set_form_state",                              Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_start",                                       Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_status",                                      Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_stop",                                        Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_stop_bot",                                    Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_weixin_qr_poll",                              Agnostic,    ControllerLocal,  REFUSED),
    op("remote_connect_weixin_qr_start",                             Agnostic,    ControllerLocal,  REFUSED),
    op("remote_create_dir",                                          Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_download_to_local_path",                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_execute",                                             Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_exists",                                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_get_tree",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_get_workspace_info",                                  Routed,      Proxied,          CLI_NO_REMOTE_WORKSPACE_UI),
    op("remote_open_workspace",                                      Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_read_dir",                                            Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_read_file",                                           Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_remove",                                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_remove_workspace",                                    Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_rename",                                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_upload_from_local_path",                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remote_write_file",                                          Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("remove_project_permission_grant",                            Agnostic,    Proxied,          HANDLED),
    op("remove_recent_workspace",                                    Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("rename_file",                                                Routed,      Proxied,          HANDLED),
    host_invoke_only("rename_session",                               Agnostic,    Proxied,          HANDLED),
    op("reorder_opened_workspaces",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("replace_mode_skill_selection",                               Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("report_canvas_runtime_error",                                Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("report_canvas_runtime_ready",                                Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("report_ide_control_result",                                  Unaudited,   ControllerLocal,  REFUSED),
    op("report_openbitfun_control_result",                            Agnostic,    ControllerLocal,  REFUSED),
    op("reset_agent_profile_config",                                 Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reset_assistant_workspace",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reset_config",                                               Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reset_memory",                                               Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reset_mode_skill_selection",                                 Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reset_workspace_persona_files",                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("resize_agent_companion_desktop_pet",                         LocalOnly,   ControllerLocal,  REFUSED),
    op("resolve_browser_dropped_file_paths",                         LocalOnly,   ControllerLocal,  REFUSED),
    op("respond_permission",                                         Agnostic,    Proxied,          HANDLED),
    op("respond_permission_batch",                                   Agnostic,    Proxied,          HANDLED),
    op("restart_app",                                                LocalOnly,   ControllerLocal,  REFUSED),
    op("restart_mcp_server",                                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("restore_session",                                            Unaudited,   Proxied,          HANDLED),
    op("restore_session_view",                                       Unaudited,   Proxied,          HANDLED),
    op("restore_session_with_turns",                                 Unaudited,   Proxied,          HANDLED),
    op("reveal_external_source_location",                            Unsupported, Proxied,          HANDLED),
    op("reveal_in_explorer",                                         LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reveal_models_dev_cache_directory",                          LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("reveal_session_storage_directory",                           Agnostic,    OperatorOnly,     REFUSED),
    op("review_platform_clear_auth_token",                           Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_issue",                                  Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_pull_request_ci_log",                    Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_pull_request_detail",                    Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_pull_request_detail_page",               Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_pull_request_review_target",             Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_pull_request_review_target_by_identity", Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_workspace_context",                      Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_get_workspace_snapshot",                     Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("review_platform_update_auth_token",                          Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("rollback_frontend_update",                                   LocalOnly,   ControllerLocal,  REFUSED),
    op("rollback_miniapp",                                           Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("rollback_session",                                           Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("rollback_session_to_turn",                                   Unsupported, Proxied,          HANDLED),
    op("run_init_agents_md",                                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("run_system_command",                                         Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_acp_json_config",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_canvas_state",                                          Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_cloud_speech_config",                                   Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_git_repo_history",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_mcp_json_config",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_merged_diff_content",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_project_permission_rules",                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("save_session_metadata",                                      Unaudited,   Proxied,          HANDLED),
    op("save_session_turn",                                          Unaudited,   Proxied,          HANDLED),
    op("save_web_search_credential",                                 Agnostic,    Proxied,          HANDLED),
    op("scan_workspace_info",                                        Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("search_build_index",                                         Unsupported,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("search_file_contents",                                       Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("search_filenames",                                           Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("search_files",                                               Routed,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("search_get_repo_status",                                     Unsupported,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("search_rebuild_index",                                       Unsupported,      Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("search_referenceable_sessions",                              Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("search_session_content",                                     Routed,      Proxied,          HANDLED),
    op("search_skill_market",                                        Unaudited,   Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("send_background_command_input",                              Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("send_mcp_app_message",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("send_system_notification",                                   LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_acp_session_config_option",                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_acp_session_model",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_active_workspace",                                       Agnostic,    Proxied,          HANDLED),
    op("set_agent_profile_config",                                   Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_config",                                                 Unaudited,   Proxied,          HANDLED),
    op("set_external_mcp_server_decision_command",                   Unsupported, Proxied,          HANDLED),
    op("set_external_mcp_servers_enabled_command",                   Unsupported, Proxied,          HANDLED),
    op("set_external_source_conflict_choice_command",                Unsupported, Proxied,          HANDLED),
    op("set_external_source_enabled_command",                        Unsupported, Proxied,          HANDLED),
    op("set_external_subagent_activation_command",                   Unsupported, Proxied,          HANDLED),
    op("set_external_subagent_model_binding_command",                Unsupported, Proxied,          HANDLED),
    op("set_external_subagents_enabled_command",                     Unsupported, Proxied,          HANDLED),
    op("set_external_tool_conflict_choice_command",                  Unsupported, Proxied,          HANDLED),
    op("set_external_tool_target_decision_command",                  Unsupported, Proxied,          HANDLED),
    op("set_external_tool_targets_enabled_command",                  Unsupported, Proxied,          HANDLED),
    op("set_file_drop_preview_target",                               LocalOnly,   ControllerLocal,  REFUSED),
    op("set_global_skill_disabled",                                  Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_macos_edit_menu_mode",                                   LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_main_window_transient_geometry",                         LocalOnly,   ControllerLocal,  REFUSED),
    op("set_miniapp_draft_storage",                                  Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_miniapp_storage",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_mode_skill_disabled",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_native_prompt_command_conflict_choice_command",          Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_prevent_sleep_enabled",                                  LocalOnly,   ControllerLocal,  REFUSED),
    op("set_primary_assistant_workspace",                            Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_session_memory_mode",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_session_thread_goal_status",                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_subagent_timeout",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("set_tray_unread_count",                                      LocalOnly,   ControllerLocal,  REFUSED),
    op("show_agent_companion_desktop_pet",                           LocalOnly,   ControllerLocal,  REFUSED),
    op("show_main_window",                                           LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_append_audio_chunk",                                  LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_append_realtime_audio",                               LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_cancel_input_session",                                LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_cancel_model_download",                               LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_cancel_realtime_response",                            LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_close_realtime_session",                              LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_commit_realtime_audio",                               LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_delete_model",                                        LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_download_model",                                      LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_finish_input_session",                                LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_get_realtime_config",                                 LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_list_models",                                         LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_save_realtime_config",                                LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_send_realtime_tool_result",                           LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_speak_realtime_text",                                 LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_start_input_session",                                 LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_start_realtime_session",                              LocalOnly,   ControllerLocal,  REFUSED),
    op("speech_verify_model",                                        LocalOnly,   ControllerLocal,  REFUSED),
    op("ssh_connect",                                                Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_delete_connection",                                      Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_disconnect",                                             Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_disconnect_all",                                         Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_get_config",                                             Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_get_server_info",                                        Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_has_stored_password",                                    Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_is_connected",                                           Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_list_config_hosts",                                      Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_list_docker_containers",                                 Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_list_port_forwards",                                     Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_list_remote_listening_ports",                            Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_list_saved_connections",                                 Agnostic,    Proxied,          HANDLED),
    op("ssh_list_wsl_distributions",                                 Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_save_connection",                                        Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_start_port_forward",                                     Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_stop_port_forward",                                      Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("ssh_test_connection",                                        Agnostic,    Proxied,          CLI_NO_DESKTOP_IDE_SURFACE),
    op("start_acp_dialog_turn",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("start_dialog_turn",                                          Routed,      Proxied,          HANDLED),
    op("start_file_watch",                                           Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("start_mcp_remote_oauth",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("start_mcp_server",                                           Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("start_search_file_contents_stream",                          Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("start_search_filenames_stream",                              Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("start_subscription_login",                                   LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("start_user_question_interaction",                           Agnostic,    Proxied,          HANDLED),
    op("startup_window_control",                                     LocalOnly,   ControllerLocal,  REFUSED),
    op("steer_dialog_turn",                                          Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("stop_acp_client",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("stop_file_watch",                                            Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("stop_mcp_server",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("submit_acp_permission_response",                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("submit_mcp_interaction_response",                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("submit_user_answers",                                        Agnostic,    Proxied,          HANDLED),
    op("subscribe_permission_requests",                              Agnostic,    Proxied,          HANDLED),
    op("terminal_ack",                                               Routed,      Proxied,          HANDLED),
    op("terminal_close",                                             Routed,      Proxied,          HANDLED),
    op("terminal_create",                                            Routed,      Proxied,          HANDLED),
    op("terminal_execute",                                           Routed,      Proxied,          HANDLED),
    op("terminal_get",                                               Routed,      Proxied,          HANDLED),
    op("terminal_get_history",                                       Routed,      Proxied,          HANDLED),
    op("terminal_get_shells",                                        LocalOnly,   Proxied,          HANDLED),
    op("terminal_has_shell_integration",                             Routed,      Proxied,          HANDLED),
    op("terminal_list",                                              Routed,      Proxied,          HANDLED),
    op("terminal_resize",                                            Routed,      Proxied,          HANDLED),
    op("terminal_send_command",                                      Routed,      Proxied,          HANDLED),
    op("terminal_shutdown_all",                                      Routed,      Proxied,          HANDLED),
    op("terminal_signal",                                            Routed,      Proxied,          HANDLED),
    op("terminal_write",                                             Routed,      Proxied,          HANDLED),
    op("test_ai_config_connection",                                  Unaudited,   Proxied,          HANDLED),
    op("test_ai_connection",                                         Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("toggle_main_window_fullscreen",                              LocalOnly,   ControllerLocal,  REFUSED),
    op("touch_session_activity",                                     Unaudited,   Proxied,          HANDLED),
    op("trigger_announcement",                                       Agnostic,    ControllerLocal,  REFUSED),
    op("unarchive_session",                                          Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_active_turn_permission_mode",                         Routed,      Proxied,          HANDLED),
    op("update_app_status",                                          Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_cron_job",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_custom_agent",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_external_integration_policy_command",                 Unsupported, Proxied,          HANDLED),
    op("update_mcp_remote_auth",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_miniapp",                                             Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_session_mode",                                        Routed,      Proxied,          HANDLED),
    op("update_session_model",                                       Unaudited,   Proxied,          HANDLED),
    op("update_session_permission_mode",                             Routed,      Proxied,          HANDLED),
    op("update_session_thread_goal_objective",                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_session_title",                                       Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_subagent",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_subagent_config",                                     Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("update_workspace_info",                                      Agnostic,    Proxied,          CLI_NOT_IMPLEMENTED),
    op("upload_image_contexts",                                      Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("validate_config",                                            Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("validate_skill_path",                                        Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("validate_tool_input",                                        Routed,      Proxied,          CLI_NOT_IMPLEMENTED),
    op("webdriver_bridge_result",                                    Unaudited,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("workspace_file_upload",                                     Routed,    Proxied,          HANDLED),
    op("worktree_bind_session",                                      Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("worktree_create",                                            Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("worktree_create_branch",                                     Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("worktree_list",                                              Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("worktree_list_projects",                                     LocalOnly,   Proxied,          CLI_NOT_IMPLEMENTED),
    op("worktree_promote",                                           Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("worktree_recreate",                                          Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("worktree_remove",                                            Unsupported, Proxied,          CLI_NOT_IMPLEMENTED),
    op("write_file_content",                                         Routed,      Proxied,          HANDLED),
];

// Binary search is a production precondition, not merely a test expectation.
// A new misplaced/duplicate row must fail every build before it can hide APIs.
const _: () = {
    let mut row = 1;
    while row < OPERATIONS.len() {
        let left = OPERATIONS[row - 1].id.as_bytes();
        let right = OPERATIONS[row].id.as_bytes();
        let mut byte = 0;
        while byte < left.len() && byte < right.len() && left[byte] == right[byte] {
            byte += 1;
        }
        let less = if byte == left.len() {
            byte < right.len()
        } else if byte == right.len() {
            false
        } else {
            left[byte] < right[byte]
        };
        assert!(less, "Product Operation Registry must be sorted and unique");
        row += 1;
    }
};
