// Boundary rules for feature assembly and optional dependency ownership.

export const servicesReqwestOwnerFeatures = [
  'account-identity',
  'announcement',
  'browser-control',
  'mcp',
  'miniapp-market',
  'miniapp-runtime',
  'models-dev',
  'remote-connect',
  'remote-ssh-concrete',
  'review-platform',
  'speech',
  'skillhub',
  'web-tools',
];

export const guardedEmptyInternalDefaultManifestPaths = [
  'src/crates/assembly/core/Cargo.toml',
  'src/crates/assembly/product-capabilities/Cargo.toml',
  'src/crates/contracts/product-domains/Cargo.toml',
  'src/crates/contracts/runtime-ports/Cargo.toml',
  'src/crates/execution/agent-runtime/Cargo.toml',
  'src/crates/execution/tool-contracts/Cargo.toml',
  'src/crates/execution/tool-execution/Cargo.toml',
  'src/crates/execution/tool-provider-groups/Cargo.toml',
  'src/crates/services/services-core/Cargo.toml',
  'src/crates/services/services-integrations/Cargo.toml',
];

export const optionalDependencyFeatureOwnerRules = [
  {
    crateName: 'app-server-protocol',
    reason:
      'App Server Protocol must keep the ACP runtime dependency behind its RPC integration',
    dependencies: [
      { depName: 'agent-client-protocol', ownerFeatures: ['rpc'] },
    ],
  },
  {
    crateName: 'services-core',
    reviewedAggregateFeatures: ['workspace-persistence'],
    reason:
      'services-core optional implementation dependencies must stay behind their exact owner capability',
    dependencies: [
      { depName: 'image', ownerFeatures: ['pet-packages'] },
      { depName: 'zip', ownerFeatures: ['pet-packages'] },
      { depName: 'uuid', ownerFeatures: ['pet-packages'] },
      { depName: 'aes-gcm', ownerFeatures: ['credential-vault'] },
      { depName: 'anyhow', ownerFeatures: ['credential-vault', 'dispatch-workspace', 'workspace-runtime', 'workspace-transfer'] },
      { depName: 'async-trait', ownerFeatures: ['permission', 'workspace-runtime'] },
      { depName: 'base64', ownerFeatures: ['pet-packages', 'credential-vault', 'filesystem'] },
      {
        depName: 'openbitfun-core-types',
        ownerFeatures: ['filesystem', 'local-storage', 'product-identity', 'workspace-persistence'],
      },
      { depName: 'openbitfun-events', ownerFeatures: ['local-storage', 'session-event-format'] },
      { depName: 'openbitfun-runtime-ports', ownerFeatures: ['permission', 'workspace-runtime', 'workspace-persistence', 'workspace-transfer'] },
      { depName: 'chrono', ownerFeatures: ['filesystem', 'local-storage', 'workspace-persistence'] },
      { depName: 'chrono-tz', ownerFeatures: ['token-usage-statistics'] },
      { depName: 'dunce', ownerFeatures: ['pet-packages', 'runtime-ownership', 'workspace-identity', 'workspace-runtime'] },
      { depName: 'fs2', ownerFeatures: ['pet-packages', 'credential-vault', 'json-io', 'local-storage', 'runtime-ownership'] },
      { depName: 'git2', ownerFeatures: ['session-git'] },
      { depName: 'globset', ownerFeatures: ['workspace-instructions'] },
      { depName: 'ignore', ownerFeatures: ['filesystem'] },
      { depName: 'libc', ownerFeatures: ['credential-vault', 'local-storage', 'process-runtime'] },
      { depName: 'rand', ownerFeatures: ['credential-vault'] },
      {
        depName: 'regex',
        ownerFeatures: [
          'diagnostics',
          'filesystem',
          'local-storage',
          'markdown',
          'workspace-instructions',
        ],
      },
      { depName: 'rusqlite', ownerFeatures: ['memory-store', 'permission', 'session-search', 'coordination-store'] },
      { depName: 'rustls', ownerFeatures: ['tls-provider'] },
      { depName: 'serde_yaml', ownerFeatures: ['markdown', 'workspace-instructions'] },
      { depName: 'similar', ownerFeatures: ['diff', 'local-storage'] },
      {
        depName: 'sha2',
        ownerFeatures: [
          'pet-packages',
          'dispatch-workspace',
          'filesystem',
          'local-storage',
          'runtime-ownership',
          'workspace-identity',
          'workspace-transfer',
        ],
      },
      { depName: 'which', ownerFeatures: ['process-runtime'] },
      { depName: 'win32job', ownerFeatures: ['process-runtime'] },
      { depName: 'windows', ownerFeatures: ['installed-apps', 'json-io', 'local-storage', 'process-runtime'] },
      {
        depName: 'tokio',
        ownerFeatures: [
          'diff',
          'credential-vault',
          'filesystem',
          'json-io',
          'local-storage',
          'permission',
          'process-runtime',
          'session-search',
          'workspace-instructions',
          'workspace-runtime',
          'workspace-text-runtime',
          'workspace-transfer',
        ],
      },
    ],
  },
  {
    crateName: 'runtime-ports',
    reviewedAggregateFeatures: ['tool-runtime-handles'],
    reason:
      'runtime-ports optional capabilities must stay behind their exact contract slice',
    dependencies: [
      { depName: 'anyhow', ownerFeatures: ['workspace-ports'] },
      { depName: 'openbitfun-core-types', ownerFeatures: ['agent-api', 'ts'] },
      { depName: 'openbitfun-product-domains', ownerFeatures: ['permission', 'product-search', 'ts'] },
      { depName: 'tokio', ownerFeatures: ['remote-exec-port', 'terminal-port', 'workspace-ports'] },
      { depName: 'tokio-util', ownerFeatures: ['workspace-ports'] },
      { depName: 'ts-rs', ownerFeatures: ['ts'] },
    ],
  },
  {
    crateName: 'agent-runtime',
    reviewedAggregateFeatures: ['native-hook-runtime'],
    reason:
      'agent-runtime optional dependencies must stay behind the full runtime or native-hook owner slice',
    dependencies: [
      { depName: 'async-trait', ownerFeatures: ['agent-runtime', 'native-hook-runtime'] },
      { depName: 'openbitfun-agent-stream', ownerFeatures: ['agent-runtime'] },
      { depName: 'openbitfun-agent-tools', ownerFeatures: ['agent-runtime'] },
      { depName: 'openbitfun-core-types', ownerFeatures: ['agent-runtime', 'definition-contracts'] },
      { depName: 'openbitfun-events', ownerFeatures: ['agent-runtime'] },
      { depName: 'openbitfun-runtime-ports', ownerFeatures: ['agent-runtime'] },
      { depName: 'openbitfun-runtime-services', ownerFeatures: ['agent-runtime'] },
      { depName: 'dashmap', ownerFeatures: ['agent-runtime'] },
      { depName: 'hex', ownerFeatures: ['agent-runtime'] },
      { depName: 'log', ownerFeatures: ['agent-runtime', 'native-hook-runtime'] },
      { depName: 'regex', ownerFeatures: ['agent-runtime', 'definition-contracts', 'native-hook-settings'] },
      { depName: 'serde', ownerFeatures: ['agent-runtime', 'definition-contracts', 'native-hook-runtime'] },
      { depName: 'serde_json', ownerFeatures: ['agent-runtime', 'definition-contracts', 'native-hook-runtime', 'native-hook-settings'] },
      { depName: 'serde_yaml', ownerFeatures: ['agent-runtime', 'definition-contracts'] },
      { depName: 'sha2', ownerFeatures: ['agent-runtime'] },
      { depName: 'thiserror', ownerFeatures: ['agent-runtime', 'definition-contracts', 'native-hook-runtime'] },
      { depName: 'tokio', ownerFeatures: ['agent-runtime', 'native-hook-runtime'] },
      { depName: 'tokio-util', ownerFeatures: ['agent-runtime'] },
      { depName: 'uuid', ownerFeatures: ['agent-runtime'] },
    ],
  },
  {
    crateName: 'core',
    reason:
      'openbitfun-core product/runtime optional dependencies must stay owned by explicit feature gates',
    dependencies: [
      { depName: 'axum', ownerFeatures: ['mcp-runtime'] },
      { depName: 'base64', ownerFeatures: ['agent-runtime', 'dispatch-store'] },
      {
        depName: 'openbitfun-ai-adapters',
        ownerFeatures: ['ai-adapter-runtime', 'subscription-auth'],
      },
      { depName: 'openbitfun-agent-runtime', ownerFeatures: ['agent-runtime'] },
      { depName: 'openbitfun-agent-workflows', ownerFeatures: ['deep-research'] },
      { depName: 'openbitfun-agent-stream', ownerFeatures: ['agent-runtime'] },
      { depName: 'openbitfun-agent-tools', ownerFeatures: ['agent-runtime', 'local-storage', 'mcp-runtime'] },
      { depName: 'openbitfun-claude-code-adapter', ownerFeatures: ['external-sources'] },
      { depName: 'openbitfun-codex-adapter', ownerFeatures: ['external-sources'] },
      { depName: 'openbitfun-external-sources', ownerFeatures: ['external-sources'] },
      { depName: 'openbitfun-legacy-migration-adapters', ownerFeatures: ['legacy-migration'] },
      { depName: 'openbitfun-opencode-adapter', ownerFeatures: ['external-sources'] },
      { depName: 'openbitfun-dsh-adapter', ownerFeatures: ['external-sources'] },
      { depName: 'openbitfun-plugin-runtime-client', ownerFeatures: ['plugin-runtime'] },
      { depName: 'openbitfun-product-capabilities', ownerFeatures: ['product-capabilities'] },
      {
        depName: 'openbitfun-product-domains',
        ownerFeatures: [
          'agent-runtime',
          'canvas-runtime',
          'function-agents',
          'plugin-source',
          'product-search',
          'tools-miniapp',
          'ts',
        ],
      },
      { depName: 'openbitfun-runtime-services', ownerFeatures: ['runtime-services'] },
      {
        depName: 'openbitfun-services-integrations',
        ownerFeatures: [
          'announcement',
          'canvas-runtime',
          'browser-control',
          'deep-research',
          'external-sources',
          'file-watch',
          'function-agents',
          'git',
          'mcp-runtime',
          'model-catalog',
          'plugin-source',
          'remote-connect',
          'remote-workspace',
          'review-platform',
          'script-tool-runtime',
          'ssh-remote',
          'tools-miniapp',
          'ts',
          'web-tools',
          'workspace-search',
        ],
      },
      {
        depName: 'openbitfun-tool-packs',
        ownerFeatures: [
          'tool-packs',
          'tools-agent-control',
          'tools-basic',
          'tools-browser-web',
          'tools-canvas',
          'tools-computer-use',
          'tools-creation',
          'tools-git',
          'tools-image-analysis',
          'tools-mcp',
          'tools-miniapp',
          'tools-pages',
        ],
      },
      { depName: 'chrono-tz', ownerFeatures: ['scheduled-jobs'] },
      { depName: 'cron', ownerFeatures: ['scheduled-jobs'] },
      { depName: 'dashmap', ownerFeatures: ['agent-runtime'] },
      { depName: 'filetime', ownerFeatures: ['agent-runtime'] },
      { depName: 'flate2', ownerFeatures: ['agent-runtime'] },
      { depName: 'fluent-bundle', ownerFeatures: ['i18n-runtime'] },
      { depName: 'fs2', ownerFeatures: ['agent-runtime'] },
      { depName: 'futures', ownerFeatures: ['agent-runtime'] },
      { depName: 'image', ownerFeatures: ['agent-runtime'] },
      { depName: 'include_dir', ownerFeatures: ['agent-runtime'] },
      { depName: 'indexmap', ownerFeatures: ['agent-runtime'] },
      { depName: 'md5', ownerFeatures: ['agent-runtime'] },
      { depName: 'reqwest', ownerFeatures: ['mcp-runtime', 'tools-miniapp'] },
      { depName: 'regex', ownerFeatures: ['agent-runtime'] },
      { depName: 'rusqlite', ownerFeatures: ['agent-runtime'] },
      { depName: 'semver', ownerFeatures: ['tools-miniapp'] },
      { depName: 'serde_yaml', ownerFeatures: ['workspace-runtime'] },
      { depName: 'similar', ownerFeatures: ['agent-runtime'] },
      { depName: 'terminal-core', ownerFeatures: ['terminal'] },
      { depName: 'notify', ownerFeatures: ['workspace-watch'] },
      { depName: 'tokio-tungstenite', ownerFeatures: ['browser-control'] },
      { depName: 'tokio-util', ownerFeatures: ['agent-runtime'] },
      { depName: 'unic-langid', ownerFeatures: ['i18n-runtime'] },
      {
        depName: 'tool-runtime',
        ownerFeatures: ['agent-runtime', 'document-read', 'web-tools'],
      },
    ],
  },
  {
    crateName: 'services-integrations',
    reason:
      'services-integrations optional runtime dependencies must stay owned by explicit integration features',
    reviewedAggregateFeatures: ['speech-realtime'],
    dependencies: [
      { depName: 'aes', ownerFeatures: ['remote-connect'] },
      { depName: 'aes-gcm', ownerFeatures: ['mcp', 'remote-connect', 'remote-persistence', 'remote-ssh-concrete'] },
      { depName: 'anyhow', ownerFeatures: ['browser-control', 'deep-research', 'mcp', 'remote-connect', 'remote-persistence', 'remote-ssh', 'remote-ssh-concrete'] },
      {
        depName: 'async-trait',
        ownerFeatures: ['deep-research', 'git', 'mcp', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete', 'review-platform', 'script-tool-runtime', 'speech', 'web-tools', 'workspace-search'],
      },
      {
        depName: 'base64',
        ownerFeatures: ['mcp', 'miniapp-runtime', 'remote-connect', 'remote-persistence', 'remote-ssh-concrete', 'speech'],
      },
      { depName: 'openbitfun-agent-runtime', ownerFeatures: ['hook-import'] },
      { depName: 'openbitfun-agent-workflows', ownerFeatures: ['deep-research'] },
      {
        depName: 'openbitfun-core-types',
        ownerFeatures: ['deep-research', 'remote-connect', 'remote-ssh-concrete', 'speech'],
      },
      { depName: 'openbitfun-product-domains', ownerFeatures: ['account-identity', 'canvas-runtime', 'function-agents', 'hook-import', 'miniapp-market', 'miniapp-runtime', 'miniapp-storage', 'plugin-source', 'remote-connect'] },
      { depName: 'openbitfun-runtime-ports', ownerFeatures: ['deep-research', 'git', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete', 'script-tool-runtime', 'web-tools'] },
      {
        depName: 'openbitfun-services-core',
        ownerFeatures: [
          'account-identity',
          'announcement',
          'browser-control',
          'git',
          'hook-import',
          'mcp',
          'miniapp-market',
          'miniapp-runtime',
          'models-dev',
          'process-tree',
          'remote-connect',
          'remote-persistence',
          'remote-ssh',
          'remote-ssh-concrete',
          'review-platform',
          'speech',
          'skillhub',
          'web-tools',
          'workspace-search',
        ],
      },
      { depName: 'bzip2', ownerFeatures: ['speech'] },
      { depName: 'chrono', ownerFeatures: ['account-identity', 'git', 'miniapp-market', 'remote-connect', 'remote-ssh-concrete', 'review-platform', 'speech', 'web-tools'] },
      { depName: 'dirs', ownerFeatures: ['account-identity', 'browser-control', 'miniapp-runtime', 'remote-connect', 'remote-ssh-concrete'] },
      { depName: 'dunce', ownerFeatures: ['plugin-source', 'workspace-search'] },
      { depName: 'fs2', ownerFeatures: ['plugin-source', 'remote-persistence', 'remote-connect'] },
      { depName: 'futures', ownerFeatures: ['mcp', 'remote-connect', 'review-platform'] },
      { depName: 'futures-util', ownerFeatures: ['speech', 'web-tools'] },
      { depName: 'git2', ownerFeatures: ['git'] },
      { depName: 'hex', ownerFeatures: ['hook-import', 'mcp', 'miniapp-market', 'plugin-source', 'remote-connect'] },
      { depName: 'hostname', ownerFeatures: ['remote-connect', 'remote-persistence'] },
      { depName: 'image', ownerFeatures: ['miniapp-market', 'remote-connect'] },
      { depName: 'local-ip-address', ownerFeatures: ['remote-connect'] },
      { depName: 'libc', ownerFeatures: ['plugin-source'] },
      { depName: 'mac_address', ownerFeatures: ['remote-connect'] },
      { depName: 'md5', ownerFeatures: ['remote-connect'] },
      { depName: 'notify', ownerFeatures: ['file-watch'] },
      { depName: 'oxc', ownerFeatures: ['canvas-runtime'] },
      { depName: 'qrcode', ownerFeatures: ['remote-connect'] },
      { depName: 'rand', ownerFeatures: ['mcp', 'remote-connect', 'remote-persistence', 'remote-ssh-concrete'] },
      // remote-ssh-concrete: one-click relay deploy fetches the signed release
      // checksum over HTTPS and verifies it on this device, because the target
      // server has no minisign and no trust root of its own.
      { depName: 'reqwest', ownerFeatures: servicesReqwestOwnerFeatures },
      { depName: 'rmcp', ownerFeatures: ['mcp'] },
      { depName: 'russh', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'russh-keys', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'russh-sftp', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'rustls', ownerFeatures: ['remote-connect'] },
      { depName: 'rustls-native-certs', ownerFeatures: ['remote-connect'] },
      { depName: 'schannel', ownerFeatures: ['remote-connect'] },
      { depName: 'sha2', ownerFeatures: ['canvas-runtime', 'hook-import', 'mcp', 'miniapp-market', 'models-dev', 'plugin-source', 'remote-connect', 'remote-persistence', 'remote-ssh', 'review-platform', 'speech'] },
      { depName: 'sherpa-onnx', ownerFeatures: ['speech'] },
      { depName: 'shellexpand', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'sse-stream', ownerFeatures: ['mcp'] },
      { depName: 'ssh_config', ownerFeatures: ['remote-ssh-concrete', 'ssh_config'] },
      { depName: 'terminal-core', ownerFeatures: ['remote-ssh', 'remote-ssh-concrete'] },
      { depName: 'tar', ownerFeatures: ['speech'] },
      { depName: 'thiserror', ownerFeatures: ['account-identity', 'browser-control', 'git', 'hook-import', 'miniapp-market', 'plugin-source', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete', 'review-platform', 'speech', 'web-tools', 'workspace-search'] },
      { depName: 'tokio-tungstenite', ownerFeatures: ['remote-connect', 'speech-realtime'] },
      { depName: 'tokio-util', ownerFeatures: ['remote-ssh', 'speech'] },
      { depName: 'urlencoding', ownerFeatures: ['canvas-runtime', 'miniapp-market', 'remote-connect', 'review-platform'] },
      { depName: 'uuid', ownerFeatures: ['canvas-runtime', 'hook-import', 'miniapp-runtime', 'miniapp-storage', 'plugin-source', 'remote-connect', 'remote-ssh-concrete', 'speech'] },
      { depName: 'which', ownerFeatures: ['miniapp-runtime', 'remote-connect', 'script-tool-runtime', 'workspace-search'] },
      { depName: 'windows', ownerFeatures: ['models-dev', 'plugin-source', 'remote-connect', 'remote-persistence', 'remote-ssh-concrete', 'review-platform'] },
      { depName: 'x25519-dalek', ownerFeatures: ['remote-connect'] },
    ],
  },
  {
    crateName: 'product-domains',
    reason:
      'product-domains optional runtime dependencies must stay owned by explicit product-domain features',
    dependencies: [
      { depName: 'dirs', ownerFeatures: ['miniapp'] },
      { depName: 'log', ownerFeatures: ['function-agents'] },
      { depName: 'hex', ownerFeatures: ['appearance-market', 'external-sources', 'miniapp', 'plugin-source'] },
      { depName: 'sha2', ownerFeatures: ['appearance-market', 'external-sources', 'miniapp', 'plugin-source'] },
      { depName: 'which', ownerFeatures: ['miniapp'] },
    ],
  },
];

function capabilityEdge(features = [], overrides = {}) {
  return {
    kind: 'normal',
    optional: false,
    rename: null,
    target: null,
    features,
    ...overrides,
  };
}

function capabilityForwarder(sourceFeature, feature, weak = false) {
  return { sourceFeature, feature, weak };
}

function capabilityConsumer(edges, forwarders = [], activators = [], aggregates = []) {
  return { edges, forwarders, activators, aggregates };
}

export const capabilityContractDependencyRules = [
  {
    packageName: 'openbitfun-runtime-ports',
    manifestPath: 'src/crates/contracts/runtime-ports/Cargo.toml',
    featureProfiles: {
      default: [],
      'agent-api': ['dep:openbitfun-core-types'],
      'git-port': [],
      'hook-function-runtime': [],
      permission: ['dep:openbitfun-product-domains'],
      'plugin-runtime': [],
      'product-search': ['dep:openbitfun-product-domains'],
      'remote-exec-port': ['dep:tokio'],
      'remote-workspace-ports': [],
      'runtime-event-port': [],
      'script-tool-runtime': [],
      'terminal-port': ['dep:tokio'],
      'tool-runtime-handles': ['workspace-ports', 'terminal-port', 'remote-exec-port'],
      'web-search-port': [],
      ts: [
        'dep:ts-rs',
        'agent-api',
        'permission',
        'openbitfun-core-types/ts',
        'openbitfun-product-domains?/ts',
      ],
      'workspace-ports': ['dep:anyhow', 'dep:tokio-util', 'dep:tokio', 'tokio/io-util'],
    },
    consumers: new Map([
      ['openbitfun-agent-runtime', capabilityConsumer([
        capabilityEdge([
          'agent-api',
          'git-port',
          'permission',
          'plugin-runtime',
          'remote-workspace-ports',
          'runtime-event-port',
          'terminal-port',
          'workspace-ports',
        ], { optional: true }),
      ], [], ['agent-runtime'])],
      ['openbitfun-agent-runtime-ipc', capabilityConsumer([
        capabilityEdge(['agent-api', 'git-port']),
      ])],
      ['openbitfun-agent-tools', capabilityConsumer([capabilityEdge()])],
      ['openbitfun-app-server', capabilityConsumer([
        capabilityEdge(['agent-api', 'product-search']),
      ])],
      ['openbitfun-app-server-protocol', capabilityConsumer(
        [capabilityEdge(['agent-api', 'git-port'])],
        [capabilityForwarder('ts', 'ts')],
      )],
      ['openbitfun-cli', capabilityConsumer([
        capabilityEdge(['agent-api', 'git-port', 'permission', 'plugin-runtime', 'workspace-ports']),
      ])],
      ['openbitfun-core', capabilityConsumer(
        [capabilityEdge(['permission', 'workspace-ports'])],
        [
          capabilityForwarder('agent-runtime', 'agent-api'),
          capabilityForwarder('agent-runtime', 'git-port'),
          capabilityForwarder('agent-runtime', 'remote-exec-port'),
          capabilityForwarder('agent-runtime', 'remote-workspace-ports'),
          capabilityForwarder('agent-runtime', 'runtime-event-port'),
          capabilityForwarder('agent-runtime', 'terminal-port'),
          capabilityForwarder('agent-runtime', 'tool-runtime-handles'),
          capabilityForwarder('agent-runtime', 'workspace-ports'),
          capabilityForwarder('opencode-plugin-host', 'hook-function-runtime'),
          capabilityForwarder('plugin-runtime', 'plugin-runtime'),
          capabilityForwarder('product-search', 'product-search'),
          capabilityForwarder('script-tool-runtime', 'script-tool-runtime'),
          capabilityForwarder('ts', 'ts'),
          capabilityForwarder('web-tools', 'web-search-port'),
        ],
        [],
        ['external-sources', 'mcp-runtime', 'opencode-plugin-host', 'product-full', 'remote-connect', 'tools-browser-web', 'tools-mcp'],
      )],
      ['openbitfun-desktop', capabilityConsumer([
        capabilityEdge(['agent-api', 'permission', 'workspace-ports']),
      ])],
      ['openbitfun-opencode-adapter', capabilityConsumer([
        capabilityEdge(['hook-function-runtime', 'plugin-runtime']),
        capabilityEdge(['script-tool-runtime'], { kind: 'dev' }),
      ])],
      ['openbitfun-opencode-plugin-host', capabilityConsumer([
        capabilityEdge(['hook-function-runtime']),
      ])],
      ['openbitfun-dsh-adapter', capabilityConsumer([
        capabilityEdge(['plugin-runtime']),
      ])],
      ['openbitfun-plugin-runtime-client', capabilityConsumer([
        capabilityEdge(['plugin-runtime']),
      ])],
      ['openbitfun-product-capabilities', capabilityConsumer([
        capabilityEdge(['plugin-runtime']),
        capabilityEdge(['agent-api'], { kind: 'dev' }),
      ])],
      ['openbitfun-runtime-services', capabilityConsumer([
        capabilityEdge([
          'git-port',
          'remote-exec-port',
          'remote-workspace-ports',
          'runtime-event-port',
          'terminal-port',
          'workspace-ports',
        ]),
      ])],
      ['openbitfun-sdk-host', capabilityConsumer([
        capabilityEdge(['agent-api']),
        capabilityEdge(['permission'], { kind: 'dev' }),
      ])],
      ['openbitfun-services-core', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [
          capabilityForwarder('permission', 'permission'),
          capabilityForwarder('workspace-runtime', 'runtime-event-port'),
          capabilityForwarder('workspace-runtime', 'workspace-ports'),
          capabilityForwarder('workspace-transfer', 'workspace-ports'),
        ],
        ['permission', 'workspace-runtime', 'workspace-persistence', 'workspace-transfer'],
      )],
      ['openbitfun-services-integrations', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [
          capabilityForwarder('deep-research', 'workspace-ports'),
          capabilityForwarder('git', 'git-port'),
          capabilityForwarder('remote-connect', 'agent-api'),
          capabilityForwarder('remote-connect', 'remote-workspace-ports'),
          // Session output delivery reads through the injected filesystem, including SSH.
          capabilityForwarder('remote-connect', 'workspace-ports'),
          capabilityForwarder('remote-ssh', 'remote-exec-port'),
          capabilityForwarder('remote-ssh', 'remote-workspace-ports'),
          capabilityForwarder('remote-ssh', 'workspace-ports'),
          capabilityForwarder('script-tool-runtime', 'script-tool-runtime'),
          capabilityForwarder('web-tools', 'web-search-port'),
        ],
        ['remote-ssh-concrete'],
        ['function-agents', 'product-full'],
      )],
      ['terminal-core', capabilityConsumer([
        capabilityEdge(['terminal-port']),
      ])],
      ['tool-runtime', capabilityConsumer([capabilityEdge(['workspace-ports'])])],
    ]),
  },
  {
    packageName: 'openbitfun-agent-tools',
    manifestPath: 'src/crates/execution/tool-contracts/Cargo.toml',
    featureProfiles: {
      default: [],
      'acp-bridge': [],
      'computer-use-contract': [],
      'element-token': [],
      'mcp-bridge': [],
    },
    consumers: new Map([
      ['openbitfun-acp', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [capabilityForwarder('client', 'acp-bridge')],
        ['server'],
        ['default'],
      )],
      ['openbitfun-agent-runtime', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [],
        ['agent-runtime'],
      )],
      ['openbitfun-agent-stream', capabilityConsumer([
        capabilityEdge([], { kind: 'dev' }),
      ])],
      ['openbitfun-cli', capabilityConsumer([capabilityEdge()])],
      ['openbitfun-core', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [
          capabilityForwarder('agent-runtime', 'computer-use-contract'),
          capabilityForwarder('mcp-runtime', 'mcp-bridge'),
        ],
        ['agent-runtime', 'local-storage'],
        [
          'dispatch-store',
          'external-sources',
          'opencode-plugin-host',
          'plugin-runtime',
          'product-search',
          'product-full',
          'remote-connect',
          'remote-workspace',
          'ssh-remote',
          'tools-basic',
          'tools-mcp',
          'workspace-runtime',
          'workspace-search',
          'workspace-watch',
        ],
      )],
      ['openbitfun-desktop', capabilityConsumer([
        // Desktop owns native control resources and consumes portable control DTOs.
        capabilityEdge(['computer-use-contract', 'element-token']),
      ])],
      ['openbitfun-services-integrations', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [capabilityForwarder('mcp', 'mcp-bridge')],
        ['remote-connect'],
        ['product-full'],
      )],
      ['tool-runtime', capabilityConsumer([capabilityEdge()])],
    ]),
  },
  {
    packageName: 'openbitfun-agent-runtime',
    manifestPath: 'src/crates/execution/agent-runtime/Cargo.toml',
    featureProfiles: {
      default: [],
      'definition-contracts': [
        // Skill declarations reuse pure hook validation without process support.
        'native-hook-settings',
        'dep:openbitfun-core-types',
        'dep:regex',
        'dep:serde',
        'dep:serde_json',
        'dep:serde_yaml',
        'dep:thiserror',
      ],
      'native-hook-settings': ['dep:regex', 'dep:serde_json'],
      'native-hook-runtime': [
        'native-hook-settings',
        'dep:async-trait',
        'dep:log',
        'dep:serde',
        'dep:serde_json',
        'dep:tokio',
        'dep:thiserror',
        'tokio/io-util',
        'tokio/macros',
        'tokio/process',
        'tokio/rt',
        // Session hook once guards and cancellation watchers.
        'tokio/sync',
        'tokio/time',
      ],
      'agent-runtime': [
        'definition-contracts',
        'native-hook-runtime',
        'dep:async-trait',
        'dep:openbitfun-agent-stream',
        'dep:openbitfun-agent-tools',
        'dep:openbitfun-core-types',
        'dep:openbitfun-events',
        'dep:openbitfun-runtime-ports',
        'dep:openbitfun-runtime-services',
        'dep:dashmap',
        'dep:hex',
        'dep:log',
        'dep:regex',
        'dep:serde',
        'dep:serde_json',
        'dep:serde_yaml',
        'dep:sha2',
        'dep:thiserror',
        'dep:tokio',
        'dep:tokio-util',
        'dep:uuid',
        'tokio/macros',
        'tokio/rt',
        'tokio/sync',
      ],
    },
    consumers: new Map([
      ['openbitfun-legacy-migration-adapters', capabilityConsumer([capabilityEdge(['definition-contracts'])])],
      ['openbitfun-acp', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [capabilityForwarder('server', 'agent-runtime')],
        ['server'],
        ['default'],
      )],
      ['openbitfun-app-server', capabilityConsumer([
        capabilityEdge(['agent-runtime']),
      ])],
      ['openbitfun-cli', capabilityConsumer([
        capabilityEdge(['agent-runtime']),
      ])],
      ['openbitfun-core', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [
          capabilityForwarder('agent-runtime', 'agent-runtime'),
        ],
        ['agent-runtime'],
        ['external-sources', 'mcp-runtime', 'opencode-plugin-host', 'plugin-runtime', 'product-search', 'product-full', 'remote-connect', 'tools-mcp'],
      )],
      ['openbitfun-desktop', capabilityConsumer([
        capabilityEdge(['agent-runtime']),
      ])],
      ['openbitfun-product-capabilities', capabilityConsumer([
        capabilityEdge(['agent-runtime'], { kind: 'dev' }),
      ])],
      ['openbitfun-sdk-host', capabilityConsumer([
        capabilityEdge(['agent-runtime']),
      ])],
      ['openbitfun-sdk-host-app', capabilityConsumer([
        capabilityEdge(['agent-runtime']),
      ])],
      ['openbitfun-server', capabilityConsumer([
        capabilityEdge(['agent-runtime']),
      ])],
      ['openbitfun-services-integrations', capabilityConsumer(
        [capabilityEdge([], { optional: true })],
        [
          capabilityForwarder('hook-import', 'native-hook-settings'),
        ],
        ['hook-import'],
        ['product-full'],
      )],
    ]),
  },
];

export const coreProductFullFeatureAssemblyRule = {
  manifestPath: 'src/crates/assembly/core/Cargo.toml',
  featureName: 'product-full',
  requiredFeatureRefs: [
    'agent-runtime',
    'product-search',
    'diagnostics',
    'diff',
    'document-read',
    'subscription-auth',
    'i18n-runtime',
    'browser-control',
    'deep-research',
    'mcp-runtime',
    'model-catalog',
    'remote-connect',
    'scheduled-jobs',
    'tools-agent-control',
    'tools-basic',
    'tools-browser-web',
    'tools-canvas',
    'tools-computer-use',
    'tools-creation',
    'tools-git',
    'tools-image-analysis',
    'tools-mcp',
    'tools-miniapp',
    'tools-pages',
    'web-tools',
    'workspace-search',
    'announcement',
    'canvas-runtime',
    'dispatch-store',
    'file-watch',
    'filesystem',
    'git',
    'local-storage',
    'process-runtime',
    'external-sources',
    'plugin-runtime',
    'opencode-plugin-host',
    'remote-workspace',
    'review-platform',
    'ssh-remote',
    'terminal',
    'workspace-runtime',
    'workspace-watch',
    'product-capabilities',
    'function-agents',
    'tool-packs',
  ],
  reason: 'openbitfun-core product-full must explicitly assemble current owner feature groups',
};

export const acpClientCoreFeatures = [
  'agent-runtime',
  'ssh-remote',
];

export const acpServerCoreFeatures = [
  'agent-runtime',
  'document-read',
  'subscription-auth',
  'external-sources',
  'tools-basic',
  'tools-git',
  'tools-mcp',
  'tools-browser-web',
  'tools-computer-use',
  'tools-image-analysis',
  'tools-agent-control',
];

export const acpClosedFeatureProfileRules = [
  {
    manifestPath: 'src/crates/interfaces/acp/Cargo.toml',
    featureName: 'default',
    requiredFeatureRefs: ['client', 'server'],
    exact: true,
    reason: 'openbitfun-acp default must preserve its complete client and server compatibility surface',
  },
  {
    manifestPath: 'src/crates/interfaces/acp/Cargo.toml',
    featureName: 'client',
    requiredFeatureRefs: [
      'openbitfun-agent-tools/acp-bridge',
      'dep:futures',
      'dep:serde',
      // The bundled DeepSeek Harness profile: `dirs` locates $DSH_HOME,
      // `semver` compares the build's minimum dsh version against the installed
      // one, and `tar` packs the profile for a remote workspace, which receives
      // it as one stream over its own transport. All three are client-only —
      // the server surface never launches an agent.
      'dep:dirs',
      'dep:semver',
      'dep:tar',
      'dep:openbitfun-core',
      ...acpClientCoreFeatures.map((feature) => `openbitfun-core/${feature}`),
    ],
    exact: true,
    reason: 'openbitfun-acp client must own only external ACP agent and SSH transport capabilities',
  },
  {
    manifestPath: 'src/crates/interfaces/acp/Cargo.toml',
    featureName: 'server',
    requiredFeatureRefs: [
      'dep:openbitfun-agent-tools',
      'dep:openbitfun-agent-runtime',
      'openbitfun-agent-runtime/agent-runtime',
      'dep:openbitfun-core-types',
      'dep:openbitfun-core',
      'dep:sha2',
      ...acpServerCoreFeatures.map((feature) => `openbitfun-core/${feature}`),
    ],
    exact: true,
    reason: 'openbitfun-acp server must preserve the reviewed Agent Runtime capability surface without SSH transport',
  },
];

export const coreClosedFeatureProfileRules = [
  {
    manifestPath: 'src/crates/interfaces/app-server/Cargo.toml',
    featureName: 'ts',
    requiredFeatureRefs: ['openbitfun-app-server-protocol/ts'],
    exact: true,
    reason: 'App Server must delegate TypeScript wire export to the protocol owner',
  },
  {
    manifestPath: 'src/crates/interfaces/app-server-protocol/Cargo.toml',
    featureName: 'default',
    requiredFeatureRefs: ['rpc'],
    exact: true,
    reason: 'App Server Protocol must preserve RPC compatibility for default consumers',
  },
  {
    manifestPath: 'src/crates/interfaces/app-server-protocol/Cargo.toml',
    featureName: 'rpc',
    requiredFeatureRefs: ['dep:agent-client-protocol'],
    exact: true,
    reason: 'App Server Protocol RPC bindings must own the ACP runtime dependency',
  },
  {
    manifestPath: 'src/crates/interfaces/app-server-protocol/Cargo.toml',
    featureName: 'ts',
    requiredFeatureRefs: [
      'openbitfun-core-types/ts',
      'openbitfun-product-domains/ts',
      'openbitfun-runtime-ports/ts',
      'dep:ts-rs',
    ],
    exact: true,
    reason: 'App Server Protocol must own the complete behavior-light TypeScript wire surface',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'default',
    requiredFeatureRefs: [],
    exact: true,
    reason: 'openbitfun-core default must stay empty so product entrypoints select capabilities explicitly',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'agent-runtime',
    requiredFeatureRefs: [
      'ai-adapter-runtime',
      'dep:openbitfun-agent-runtime',
      'openbitfun-agent-runtime/agent-runtime',
      'dep:openbitfun-agent-content',
      'dep:openbitfun-agent-stream',
      'dep:openbitfun-agent-tools',
      'openbitfun-agent-tools/computer-use-contract',
      'openbitfun-runtime-ports/agent-api',
      'openbitfun-runtime-ports/git-port',
      'openbitfun-runtime-ports/remote-exec-port',
      'openbitfun-runtime-ports/remote-workspace-ports',
      'openbitfun-runtime-ports/runtime-event-port',
      'openbitfun-runtime-ports/terminal-port',
      'openbitfun-runtime-ports/tool-runtime-handles',
      'openbitfun-runtime-ports/workspace-ports',
      'dep:base64',
      'dep:dashmap',
      'dep:filetime',
      'dep:flate2',
      'dep:fs2',
      'dep:futures',
      'dep:include_dir',
      'dep:indexmap',
      'dep:image',
      'dep:md5',
      'dep:rusqlite',
      'dep:regex',
      'dep:similar',
      'dep:tokio-util',
      'dep:tool-runtime',
      // Complete ExecCommand constraint syntax facts live in the tool owner.
      'tool-runtime/shell-analysis',
      'openbitfun-services-core/memory-store',
      'openbitfun-services-core/coordination-store',
      'openbitfun-services-core/session-event-format',
      'openbitfun-services-core/permission',
      'openbitfun-services-core/runtime-ownership',
      'openbitfun-services-core/session-git',
      'openbitfun-services-core/token-usage-statistics',
      'openbitfun-services-core/workspace-text-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'dep:openbitfun-product-domains',
      'openbitfun-product-domains/external-sources',
      'runtime-services',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'tokio/io-util',
      'tokio/macros',
      'tokio/rt',
      'tokio/time',
    ],
    allowedTransitiveFeatureRefs: [
      'workspace-search',
      'scheduled-jobs',
    ],
    exact: true,
    reason:
      'openbitfun-core agent-runtime is the reviewed Core Agent Runtime owner closure, not a product-full alias',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'product-search',
    requiredFeatureRefs: [
      'agent-runtime',
      'dep:openbitfun-product-domains',
      'openbitfun-runtime-ports/product-search',
      'openbitfun-services-core/session-search',
    ],
    allowedTransitiveFeatureRefs: [
      'ai-adapter-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'runtime-services',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'workspace-search',
      'scheduled-jobs',
    ],
    exact: true,
    reason:
      'openbitfun-core product-search must layer the derived Session index over the reviewed Agent Runtime baseline',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'i18n-runtime',
    requiredFeatureRefs: ['dep:fluent-bundle', 'dep:unic-langid'],
    exact: true,
    reason:
      'i18n-runtime must own only the backend Fluent bundle and language identifier implementation',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'diagnostics',
    requiredFeatureRefs: ['openbitfun-services-core/diagnostics'],
    exact: true,
    reason: 'openbitfun-core diagnostics must preserve only the reusable diagnostic redaction facade',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'diff',
    requiredFeatureRefs: ['openbitfun-services-core/diff'],
    exact: true,
    reason: 'openbitfun-core diff must preserve only the reusable local diff facade',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'external-sources',
    requiredFeatureRefs: [
      'agent-runtime',
      'model-catalog',
      'mcp-runtime',
      'script-tool-runtime',
      'dep:openbitfun-opencode-adapter',
      'dep:openbitfun-dsh-adapter',
      'dep:openbitfun-pi-adapter',
      'dep:openbitfun-claude-code-adapter',
      'dep:openbitfun-codex-adapter',
      'dep:openbitfun-external-sources',
      'openbitfun-services-integrations/hook-import',
      'plugin-source',
      'file-watch',
      'workspace-watch',
    ],
    allowedTransitiveFeatureRefs: [
      'ai-adapter-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'remote-workspace',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'runtime-services',
      'git',
      'review-platform',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'workspace-search',
      'scheduled-jobs',
      'plugin-source',
    ],
    exact: true,
    reason:
      'openbitfun-core external-sources must compose only the reviewed source adapters, watchers, and Core runtime owner',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'plugin-runtime',
    requiredFeatureRefs: [
      'external-sources',
      'dep:openbitfun-plugin-runtime-client',
      'openbitfun-runtime-ports/plugin-runtime',
    ],
    allowedTransitiveFeatureRefs: [
      'agent-runtime',
      'model-catalog',
      'mcp-runtime',
      'script-tool-runtime',
      'file-watch',
      'workspace-watch',
      'ai-adapter-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'remote-workspace',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'runtime-services',
      'git',
      'review-platform',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'workspace-search',
      'scheduled-jobs',
      'plugin-source',
    ],
    exact: true,
    reason:
      'openbitfun-core plugin-runtime must add only the executable client boundary to external source composition',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'opencode-plugin-host',
    requiredFeatureRefs: [
      'plugin-runtime',
      'remote-connect',
      'git',
      'dep:openbitfun-opencode-plugin-host',
      'openbitfun-runtime-ports/hook-function-runtime',
    ],
    allowedTransitiveFeatureRefs: [
      'agent-runtime',
      'external-sources',
      'model-catalog',
      'mcp-runtime',
      'script-tool-runtime',
      'plugin-source',
      'file-watch',
      'workspace-watch',
      'ai-adapter-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'runtime-services',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'workspace-search',
      'scheduled-jobs',
    ],
    exact: true,
    reason:
      'the managed OpenCode Host must compose one typed Hook/function execution port without restoring the retired LSP runtime or exposing Host wire DTOs',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'model-catalog',
    requiredFeatureRefs: [
      'ai-adapter-runtime',
      'openbitfun-services-integrations/models-dev',
      'runtime-services',
    ],
    exact: true,
    reason: 'model-catalog must own built-in AI projection, models.dev refresh, and catalog update events',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'mcp-runtime',
    requiredFeatureRefs: [
      'agent-runtime',
      'openbitfun-agent-tools/mcp-bridge',
      'dep:axum',
      'dep:reqwest',
      'openbitfun-services-integrations/mcp',
      'tokio/rt-multi-thread',
    ],
    allowedTransitiveFeatureRefs: [
      'ai-adapter-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'runtime-services',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'workspace-search',
      'scheduled-jobs',
    ],
    exact: true,
    reason: 'mcp-runtime must layer the Core MCP tool bridge and service on the Agent Runtime',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'remote-connect',
    requiredFeatureRefs: [
      'agent-runtime',
      'git',
      'model-catalog',
      'openbitfun-services-integrations/remote-connect',
      'openbitfun-services-core/workspace-transfer',
    ],
    allowedTransitiveFeatureRefs: [
      'ai-adapter-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'runtime-services',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'workspace-search',
      'scheduled-jobs',
    ],
    exact: true,
    reason: 'remote-connect must layer phone relay integration on the Agent Runtime and model catalog',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'workspace-search',
    requiredFeatureRefs: [
      'workspace-runtime',
      'openbitfun-services-integrations/workspace-search',
    ],
    allowedTransitiveFeatureRefs: ['filesystem', 'local-storage', 'process-runtime'],
    exact: true,
    reason: 'workspace-search must layer indexed search on the local workspace runtime',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'browser-control',
    requiredFeatureRefs: [
      'dep:tokio-tungstenite',
      'openbitfun-services-integrations/browser-control',
      'tokio/net',
      'tokio/rt',
      'tokio/time',
    ],
    exact: true,
    reason: 'browser-control must own only the CDP browser adapter',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'web-tools',
    requiredFeatureRefs: [
      'openbitfun-runtime-ports/web-search-port',
      'openbitfun-services-core/credential-vault',
      'openbitfun-services-integrations/web-tools',
      'tool-runtime/web-readable',
    ],
    exact: true,
    reason:
      'web-tools must own the WebSearch port, device-local credential vault, provider integrations, and readable-content support',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'deep-research',
    requiredFeatureRefs: [
      'dep:openbitfun-agent-workflows',
      'openbitfun-services-integrations/deep-research',
    ],
    exact: true,
    reason: 'deep-research must own only research report post-processing',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'script-tool-runtime',
    requiredFeatureRefs: [
      'openbitfun-runtime-ports/script-tool-runtime',
      'openbitfun-services-integrations/script-tool-runtime',
    ],
    exact: true,
    reason: 'script-tool-runtime must own only external script tool execution support',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'scheduled-jobs',
    requiredFeatureRefs: ['dep:chrono-tz', 'dep:cron'],
    exact: true,
    reason: 'scheduled-jobs is an additive Agent Runtime modifier for cron parsing and timezone scheduling',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'document-read',
    requiredFeatureRefs: ['tool-runtime?/document-read'],
    exact: true,
    reason:
      'document-read must add conversion only when the Agent tool runtime owner is selected',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'subscription-auth',
    requiredFeatureRefs: ['openbitfun-ai-adapters?/subscription-auth'],
    exact: true,
    reason:
      'subscription-auth must add local credential resolution only when the AI adapter runtime owner is selected',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'ai-adapter-runtime',
    requiredFeatureRefs: ['dep:openbitfun-ai-adapters'],
    exact: true,
    reason:
      'ai-adapter-runtime must own provider protocol clients without implicitly enabling local subscription credentials',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-basic',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/basic',
      'workspace-search',
    ],
    allowedTransitiveFeatureRefs: [
      'filesystem',
      'local-storage',
      'process-runtime',
      'workspace-runtime',
    ],
    exact: true,
    reason: 'tools-basic must compose only the baseline code-agent tool dependencies',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-git',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/git',
      'git',
      'review-platform',
    ],
    exact: true,
    reason: 'tools-git must compose only Git, worktree, and review platform tools',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-mcp',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/mcp',
      'mcp-runtime',
    ],
    allowedTransitiveFeatureRefs: [
      'agent-runtime',
      'ai-adapter-runtime',
      'filesystem',
      'local-storage',
      'process-runtime',
      'terminal',
      'workspace-runtime',
      'product-capabilities',
      'runtime-services',
      'tool-packs',
      'tools-basic',
      'tools-agent-control',
      'workspace-search',
      'scheduled-jobs',
    ],
    exact: true,
    reason: 'tools-mcp must compose only MCP catalog tools and their service owner',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-browser-web',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/browser-web',
      'browser-control',
      'web-tools',
    ],
    exact: true,
    reason: 'tools-browser-web must compose only browser control and web research tools',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-computer-use',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/computer-use',
    ],
    exact: true,
    reason: 'tools-computer-use must own only the injected desktop automation tool',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-image-analysis',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/image-analysis',
    ],
    exact: true,
    reason: 'tools-image-analysis must own only explicit image inspection tools',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-pages',
    requiredFeatureRefs: ['openbitfun-tool-packs/pages'],
    exact: true,
    reason: 'tools-pages owns account publishing tools without MiniApp runtime dependencies',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-miniapp',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/miniapp',
      'dep:openbitfun-product-domains',
      'openbitfun-product-domains/appearance-market',
      'openbitfun-product-domains/miniapp',
      'openbitfun-services-integrations/miniapp-runtime',
      'openbitfun-services-integrations/miniapp-market',
      'runtime-services',
      'dep:reqwest',
      'dep:semver',
    ],
    exact: true,
    reason: 'tools-miniapp must compose only MiniApp publication and runtime tool dependencies',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-creation',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/creation',
    ],
    exact: true,
    reason: 'tools-creation must own only Creative product-authoring tools',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-canvas',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/canvas',
      'canvas-runtime',
    ],
    exact: true,
    reason: 'tools-canvas must compose only Canvas tools and runtime IO',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'tools-agent-control',
    requiredFeatureRefs: [
      'openbitfun-tool-packs/agent-control',
      'scheduled-jobs',
    ],
    exact: true,
    reason: 'tools-agent-control must compose only session, subagent, planning, and scheduled-job tools',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'function-agents',
    requiredFeatureRefs: [
      'ai-adapter-runtime',
      'dep:openbitfun-product-domains',
      'openbitfun-product-domains/function-agents',
      'openbitfun-services-integrations/function-agents',
      'runtime-services',
    ],
    exact: true,
    reason:
      'openbitfun-core function-agents must own only function-agent contracts and concrete Git/AI adapters',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'canvas-runtime',
    requiredFeatureRefs: [
      'dep:openbitfun-product-domains',
      'openbitfun-services-integrations/canvas-runtime',
    ],
    exact: true,
    reason:
      'openbitfun-core canvas-runtime must extend only the product domain surface with Canvas runtime IO',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'default',
    requiredFeatureRefs: [],
    exact: true,
    reason: 'services-core default profile must stay empty so consumers select capabilities explicitly',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'tls-provider',
    requiredFeatureRefs: ['dep:rustls'],
    exact: true,
    reason: 'services-core TLS provider owner must select only the workspace Rustls implementation',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'diagnostics',
    requiredFeatureRefs: ['dep:regex'],
    exact: true,
    reason: 'services-core diagnostics must own only deterministic diagnostic-log redaction',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'session-search',
    requiredFeatureRefs: [
      'dep:openbitfun-product-domains',
      'dep:rusqlite',
      'dep:tokio',
      'tokio/rt',
    ],
    exact: true,
    reason:
      'services-core session-search must own only the rebuildable SQLite index and its bounded blocking runtime',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'diff',
    requiredFeatureRefs: ['dep:similar', 'dep:tokio', 'tokio/rt', 'tokio/time'],
    exact: true,
    reason: 'services-core diff must own only local text diff calculation and its bounded async runtime',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'product-identity',
    requiredFeatureRefs: ['dep:openbitfun-core-types'],
    exact: true,
    reason: 'services-core product identity must remain a behavior-light stable contract re-export',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'filesystem',
    requiredFeatureRefs: [
      'dep:base64',
      'dep:chrono',
      'dep:ignore',
      'dep:openbitfun-core-types',
      'dep:regex',
      'dep:sha2',
      'dep:tokio',
      'tokio/fs',
      'tokio/rt',
      'tokio/sync',
    ],
    exact: true,
    reason: 'services-core filesystem must own only local file operations and recursive search dependencies',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'json-io',
    requiredFeatureRefs: [
      'dep:fs2',
      'dep:tokio',
      'dep:windows',
      'tokio/fs',
      'tokio/rt',
      'tokio/sync',
      'tokio/time',
      'windows/Win32_Foundation',
      'windows/Win32_Storage_FileSystem',
    ],
    exact: true,
    reason: 'services-core json-io must own only generic locked and atomic JSON file IO',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'local-storage',
    requiredFeatureRefs: [
      'dep:openbitfun-core-types',
      'dep:openbitfun-events',
      'dep:chrono',
      'dep:fs2',
      'dep:libc',
      'dep:regex',
      'dep:sha2',
      'dep:similar',
      'dep:tokio',
      'dep:windows',
      'tokio/fs',
      'tokio/rt',
      'tokio/sync',
      'tokio/time',
      'windows/Win32_Foundation',
      'windows/Win32_Storage_FileSystem',
    ],
    exact: true,
    reason: 'services-core local-storage must own durable JSON, session, usage, and cleanup primitives',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'memory-store',
    requiredFeatureRefs: ['dep:rusqlite'],
    exact: true,
    reason: 'services-core memory-store must own only the durable Memory SQLite format',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'token-usage-statistics',
    requiredFeatureRefs: ['local-storage', 'dep:chrono-tz'],
    exact: true,
    reason: 'services-core token-usage-statistics must add only dashboard aggregation and IANA time-zone support',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'process-runtime',
    requiredFeatureRefs: [
      'dep:libc',
      'dep:tokio',
      'dep:which',
      'dep:win32job',
      'dep:windows',
      'tokio/io-util',
      'tokio/process',
      'tokio/rt',
      'tokio/time',
      'windows/Win32_Foundation',
      'windows/Win32_System_Diagnostics_ToolHelp',
      'windows/Win32_System_JobObjects',
      'windows/Win32_System_Threading',
    ],
    exact: true,
    reason: 'services-core process-runtime must own command lookup and supervised child lifecycle dependencies',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-instructions',
    requiredFeatureRefs: [
      'dep:globset',
      'dep:regex',
      'dep:serde_yaml',
      'dep:tokio',
      'tokio/fs',
      'tokio/io-util',
      'tokio/rt',
    ],
    exact: true,
    reason: 'services-core workspace-instructions must own declarative instruction discovery, scope parsing, and glob expansion only',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-text-runtime',
    requiredFeatureRefs: ['dep:tokio', 'tokio/rt'],
    exact: true,
    reason: 'services-core workspace-text-runtime must own only bounded asynchronous local workspace reads',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-transfer',
    requiredFeatureRefs: [
      'dep:anyhow', 'dep:openbitfun-runtime-ports',
      'openbitfun-runtime-ports/workspace-ports', 'dep:sha2', 'dep:tokio',
      'tokio/fs', 'tokio/io-util', 'tokio/rt', 'tokio/sync',
    ],
    exact: true,
    reason: 'workspace-transfer owns bounded upload IO and optimistic commit through injected workspace ports, without process or transport implementations',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-runtime',
    requiredFeatureRefs: [
      'dep:anyhow',
      'dep:async-trait',
      'dep:openbitfun-runtime-ports',
      'openbitfun-runtime-ports/runtime-event-port',
      'openbitfun-runtime-ports/workspace-ports',
      'dep:dunce',
      'dep:filetime',
      'process-runtime',
      'tokio/fs',
      'tokio/io-util',
      'tokio/sync',
    ],
    exact: true,
    reason: 'services-core workspace-runtime must compose process supervision with local workspace IO and ports',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'session-git',
    requiredFeatureRefs: ['local-storage', 'dep:git2'],
    exact: true,
    reason: 'services-core session-git must own only the libgit2-backed memory workspace capability',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-identity',
    requiredFeatureRefs: ['dep:dunce', 'dep:sha2'],
    exact: true,
    reason: 'services-core workspace-identity must own only canonical workspace path identity support',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'dispatch-store',
    requiredFeatureRefs: [
      'dep:base64',
      'local-storage',
      'openbitfun-services-core/dispatch-workspace',
    ],
    exact: true,
    reason: 'openbitfun-core dispatch-store must expose only the durable dispatch index facade',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'filesystem',
    requiredFeatureRefs: ['openbitfun-services-core/filesystem'],
    exact: true,
    reason: 'openbitfun-core filesystem must select only the concrete local filesystem owner',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'local-storage',
    requiredFeatureRefs: ['dep:openbitfun-agent-tools', 'openbitfun-services-core/local-storage'],
    exact: true,
    reason: 'openbitfun-core local-storage must select only reusable local persistence owners',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'process-runtime',
    requiredFeatureRefs: ['openbitfun-services-core/process-runtime'],
    exact: true,
    reason: 'openbitfun-core process-runtime must select only managed process and local action owners',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'terminal',
    requiredFeatureRefs: ['dep:terminal-core'],
    exact: true,
    reason: 'openbitfun-core terminal must select only the standalone terminal service owner',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'workspace-runtime',
    requiredFeatureRefs: [
      'dep:serde_yaml',
      'filesystem',
      'local-storage',
      'process-runtime',
      'openbitfun-services-core/markdown',
      'openbitfun-services-core/workspace-identity',
      'openbitfun-services-core/workspace-instructions',
      'openbitfun-services-core/workspace-runtime',
      'openbitfun-services-core/workspace-persistence',
    ],
    exact: true,
    reason: 'openbitfun-core workspace-runtime must select only local workspace and runtime layout owners',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'workspace-watch',
    requiredFeatureRefs: ['workspace-runtime', 'dep:notify'],
    allowedTransitiveFeatureRefs: ['filesystem', 'local-storage', 'process-runtime'],
    exact: true,
    reason: 'openbitfun-core workspace-watch must extend only local workspace runtime with identity watching',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'remote-workspace',
    requiredFeatureRefs: [
      'workspace-runtime',
      'dep:openbitfun-services-integrations',
      'openbitfun-services-integrations/remote-ssh',
    ],
    allowedTransitiveFeatureRefs: ['filesystem', 'local-storage', 'process-runtime'],
    exact: true,
    reason: 'openbitfun-core remote-workspace must add only the remote workspace service surface',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'announcement',
    requiredFeatureRefs: ['openbitfun-services-integrations/announcement'],
    exact: true,
    reason: 'openbitfun-core announcement must select only the announcement owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'file-watch',
    requiredFeatureRefs: ['openbitfun-services-integrations/file-watch'],
    exact: true,
    reason: 'openbitfun-core file-watch must select only the file-watch owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'git',
    requiredFeatureRefs: ['openbitfun-services-integrations/git'],
    exact: true,
    reason: 'openbitfun-core git must select only the Git owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'review-platform',
    requiredFeatureRefs: ['openbitfun-services-integrations/review-platform'],
    exact: true,
    reason:
      'openbitfun-core review-platform must select only the review platform owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'service-integrations',
    requiredFeatureRefs: ['announcement', 'file-watch', 'git', 'review-platform'],
    exact: true,
    reason:
      'openbitfun-core service-integrations is a compatibility facade group, not a product capability umbrella',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'ssh-remote',
    requiredFeatureRefs: [
      'remote-workspace',
      'openbitfun-services-integrations/remote-ssh-concrete',
    ],
    allowedTransitiveFeatureRefs: [
      'filesystem',
      'local-storage',
      'process-runtime',
      'workspace-runtime',
    ],
    exact: true,
    reason:
      'openbitfun-core ssh-remote must extend only the remote workspace surface with concrete SSH and must not pull product Dispatch assembly',
  },
];

export const ownerCrateFeatureAssemblyRules = [
  {
    manifestPath: 'src/crates/execution/tool-provider-groups/Cargo.toml',
    reason: 'tool-packs must keep product feature groups explicit and default-light',
    requiredProductFullFeatures: [
      'basic',
      'git',
      'mcp',
      'browser-web',
      'computer-use',
      'image-analysis',
      'miniapp',
      'pages',
      'creation',
      'canvas',
      'agent-control',
    ],
  },
  {
    manifestPath: 'src/crates/services/services-integrations/Cargo.toml',
    reason: 'services-integrations must keep integration feature groups explicit and default-light',
    optionalDependencyAggregateFeatures: [
      'function-agents',
      'mcp',
      'miniapp-market',
      'remote-ssh-concrete',
      'script-tool-runtime',
    ],
    requiredProductFullFeatures: [
      'announcement',
      'browser-control',
      'canvas-runtime',
      'deep-research',
      'file-watch',
      'function-agents',
      'git',
      'hook-import',
      'miniapp-runtime',
      'mcp',
      'models-dev',
      'plugin-source',
      'remote-connect',
      'remote-ssh',
      'remote-ssh-concrete',
      'review-platform',
      'script-tool-runtime',
      'web-tools',
      'workspace-search',
    ],
  },
  {
    manifestPath: 'src/crates/contracts/product-domains/Cargo.toml',
    reason: 'product-domains must keep product domain feature groups explicit and default-light',
    requiredProductFullFeatures: [
      'appearance-market',
      'plugin-source',
      'miniapp',
      'function-agents',
      'external-sources',
      'legacy-migration',
    ],
  },
];

export function reviewedOptionalDependencyAggregateFeatures(manifestPath) {
  const features = new Set(
    coreClosedFeatureProfileRules
      .filter((profile) => profile.manifestPath === manifestPath)
      .map((profile) => profile.featureName),
  );
  if (coreProductFullFeatureAssemblyRule.manifestPath === manifestPath) {
    features.add(coreProductFullFeatureAssemblyRule.featureName);
  }
  const ownerAssembly = ownerCrateFeatureAssemblyRules.find((profile) =>
    profile.manifestPath === manifestPath);
  if (ownerAssembly) {
    features.add('product-full');
    for (const feature of ownerAssembly.optionalDependencyAggregateFeatures ?? []) {
      features.add(feature);
    }
  }
  return features;
}
