import type { ComponentMeta } from "../../registry.types";

export const multiSelectMeta = {
  category: "form",
  description: "A searchable multi-value selector with an embedded search header and structured options on one anchored surface, plus tags, select-all, and explicit value creation.",
  maturity: "stable",
  name: "MultiSelect",
  props: [
    { name: "options", type: "readonly ComboboxOption[]" },
    { name: "value", type: "readonly ComboboxValue[]" },
    { name: "onValueChange", type: "(value: ComboboxValue[]) => void" },
    { name: "onCreateValue", type: "(input: string) => ComboboxValue | void" },
    { defaultValue: "false", name: "clearable", type: "boolean" },
    { defaultValue: "3", name: "maxVisibleTags", type: "number" },
    { name: "selectionSummary", type: "ReactNode" },
    { defaultValue: "false", name: "showSelectAll", type: "boolean" },
    { defaultValue: "md", name: "size", type: "sm | md | lg" },
  ],
  states: ["default", "open", "searching", "custom", "invalid", "disabled", "loading", "empty"],
  tokens: [
    "color.field.background",
    "color.field.backgroundHover",
    "color.field.border",
    "color.field.borderHover",
    "color.field.borderFocus",
    "color.content.primary",
    "color.content.secondary",
    "color.content.muted",
    "color.content.disabled",
    "color.control.highlight.background",
    "color.action.neutral.content",
    "color.action.neutral.surface",
    "color.border.subtle",
    "color.surface.panel",
    "color.focus.ring",
    "color.status.danger.border",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "control.select.paddingInline",
    "control.select.radius",
    "control.select.indicatorSize",
    "control.select.contentGap",
    "control.select.trailingInset",
    "control.iconButton.xsSize",
    "overlay.menu.inlineSize",
    "overlay.menu.surfacePadding",
    "overlay.menu.surfaceRadius",
    "overlay.menu.itemIconSize",
    "shadow.menu",
    "type.label.selected.fontWeight",
  ],
} as const satisfies ComponentMeta;
