import type { ComponentMeta } from "../../registry.types";

export const statusPillMeta = {
  category: "feedback",
  description: "A compact semantic status label with an optional decorative leading indicator.",
  maturity: "stable",
  name: "StatusPill",
  props: [
    { name: "children", type: "ReactNode" },
    { name: "leading", type: "ReactNode" },
    { defaultValue: "false", name: "emphasis", type: "boolean" },
    { defaultValue: "success", name: "tone", type: "neutral | accent | info | success | warning | danger" },
    { defaultValue: "pill", name: "shape", type: "pill | rounded" },
  ],
  states: ["neutral", "accent", "info", "success", "warning", "danger"],
  tokens: [
    "color.action.neutral.surface",
    "color.status.info.emphasis",
    "color.status.success.emphasis",
    "color.status.warning.emphasis",
    "color.status.danger.emphasis",
    "type.statusPill.lineHeight",
    "color.content.secondary",
    "color.accent.default",
    "color.status.info.content",
    "color.status.info.surface",
    "color.status.success.content",
    "color.status.success.surface",
    "color.status.warning.content",
    "color.status.warning.surface",
    "color.status.danger.content",
    "color.status.danger.surface",
    "control.statusPill.gap",
    "control.statusPill.paddingBlock",
    "control.statusPill.paddingInline",
    "control.statusPill.radius",
    "radius.sm",
    "control.statusPill.iconSize",
    "type.meta.fontSize",
  ],
} as const satisfies ComponentMeta;
