// Generated by scripts/mobile-ui-design-system.mjs. Do not edit.
import SwiftUI
import UIKit

struct MobileTypographyToken {
    let size: CGFloat
    let lineHeight: CGFloat
    let weight: UIFont.Weight
    let textStyle: UIFont.TextStyle

    private var scaledFont: UIFont {
        UIFontMetrics(forTextStyle: textStyle).scaledFont(
            for: UIFont.systemFont(ofSize: size, weight: weight)
        )
    }

    var font: Font { Font(scaledFont) }
    var lineSpacing: CGFloat {
        let scaledLineHeight = UIFontMetrics(forTextStyle: textStyle).scaledValue(for: lineHeight)
        return max(0, scaledLineHeight - scaledFont.lineHeight)
    }
}

enum MobileDesignColors {
    static let startWindowBackground = dynamic(light: 0xFFFFFFFF, dark: 0xFF000000)
    static let transparent = dynamic(light: 0x00000000, dark: 0x00000000)
    static let pageBg = dynamic(light: 0xFFFFFFFF, dark: 0xFF151514)
    static let pageBgFade = dynamic(light: 0x00FFFFFF, dark: 0x00151514)
    static let pageBgOverlay = dynamic(light: 0xB8FFFFFF, dark: 0xB8151514)
    static let ink = dynamic(light: 0xFF171717, dark: 0xFFF4F3EF)
    static let muted = dynamic(light: 0xFF706F6A, dark: 0xFFAAA8A0)
    static let subtle = dynamic(light: 0xFFA5A39B, dark: 0xFF77756E)
    static let line = dynamic(light: 0xFFE9E7E2, dark: 0xFF363531)
    static let card = dynamic(light: 0xFFFFFFFF, dark: 0xFF252522)
    static let cardOverlay = dynamic(light: 0xCCFFFFFF, dark: 0xCC252522)
    static let accent = dynamic(light: 0xFF111111, dark: 0xFF5B5954)
    static let fileLink = dynamic(light: 0xFF2563EB, dark: 0xFF60A5FA)
    static let primaryAction = dynamic(light: 0xFF111111, dark: 0xFF454540)
    static let contentOnAction = dynamic(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
    static let connectHeroBg = dynamic(light: 0xFFE6EDFF, dark: 0xFF2B2B29)
    static let connectHeroAccent = dynamic(light: 0xFF9DB4FF, dark: 0xFF4A4944)
    static let connectHeroSecondary = dynamic(light: 0xFFC9C5FF, dark: 0xFF3C3B38)
    static let connectHeroSurface = dynamic(light: 0xFFF8FAFF, dark: 0xFF252522)
    static let connectScanAccent = dynamic(light: 0xFFFFD021, dark: 0xFFFFD021)
    static let scrim = dynamic(light: 0x44000000, dark: 0x44000000)
    static let shellScrim = dynamic(light: 0x24000000, dark: 0x24000000)
    static let mediaBackground = dynamic(light: 0xFF000000, dark: 0xFF000000)
    static let mediaScrim = dynamic(light: 0xB8000000, dark: 0xB8000000)
    static let mediaControlBackground = dynamic(light: 0x8C000000, dark: 0x8C000000)
    static let toastBackground = dynamic(light: 0xD1171717, dark: 0xD1171717)
    static let shadowFaint = dynamic(light: 0x08000000, dark: 0x08000000)
    static let shadowSubtle = dynamic(light: 0x12000000, dark: 0x12000000)
    static let shadowMedium = dynamic(light: 0x18000000, dark: 0x18000000)
    static let shadowStrong = dynamic(light: 0x24000000, dark: 0x24000000)
    static let floatingBorder = dynamic(light: 0x18000000, dark: 0x18000000)
    static let soft = dynamic(light: 0xFFF4F3F0, dark: 0xFF2D2C28)
    static let floatingPanelBg = dynamic(light: 0xFFF7F7F5, dark: 0xFF1E1E1C)
    static let sidebarBg = dynamic(light: 0xFFF8F8F9, dark: 0xFF0E0E10)
    static let sidebarBgFade = dynamic(light: 0x00F8F8F9, dark: 0x000E0E10)
    static let sidebarRaised = dynamic(light: 0xFFFFFFFF, dark: 0xFF1C1C1F)
    static let sidebarLine = dynamic(light: 0x14101A27, dark: 0x1FFFFFFF)
    static let sidebarHover = dynamic(light: 0xFFF3F3F5, dark: 0x0FFFFFFF)
    static let sidebarSelection = dynamic(light: 0x14000000, dark: 0x1FFFFFFF)
    static let sidebarInk = dynamic(light: 0xCC000000, dark: 0xFFE8E8E8)
    static let sidebarMuted = dynamic(light: 0x99000000, dark: 0xFFB0B0B0)
    static let sidebarSubtle = dynamic(light: 0x66000000, dark: 0xFF858585)
    static let statusSuccess = dynamic(light: 0xFF27C46A, dark: 0xFF3BD47B)
    static let statusDanger = dynamic(light: 0xFFE04F4F, dark: 0xFFFF6B6B)
    static let codeLineNumber = dynamic(light: 0xFFAAA69D, dark: 0xFF77756E)
    static let codeKeyword = dynamic(light: 0xFF8F3F71, dark: 0xFFD99AC4)
    static let codeString = dynamic(light: 0xFF477A4A, dark: 0xFF9BCB9D)
    static let codeNumber = dynamic(light: 0xFF9A5B13, dark: 0xFFE3B36D)
    static let codeComment = dynamic(light: 0xFF7A8078, dark: 0xFF96958D)
    static let codeFunction = dynamic(light: 0xFF2C6693, dark: 0xFF8CBCE0)
    static let codeType = dynamic(light: 0xFF865A20, dark: 0xFFD5B27F)
    static let codeConstant = dynamic(light: 0xFFA04444, dark: 0xFFE79A9A)
    static let codeProperty = dynamic(light: 0xFF466D78, dark: 0xFF9CC8D0)
    static let codeTargetBg = dynamic(light: 0xFFFFF1BE, dark: 0xFF5A4E24)
    static let brandDot = dynamic(light: 0xFF16B9CE, dark: 0xFF16B9CE)
    static let welcomeDock = dynamic(light: 0xFF171917, dark: 0xFF171917)
    static let welcomeButton = dynamic(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
    static let welcomeButtonLabel = dynamic(light: 0xFF171917, dark: 0xFF171917)
    static let welcomeSecondary = dynamic(light: 0xFFB9BCB9, dark: 0xFFB9BCB9)
    static let statusWarning = dynamic(light: 0xFFFF8C00, dark: 0xFFFF8C00)

    private static func dynamic(light: UInt32, dark: UInt32) -> Color {
        Color(uiColor: UIColor { traits in
            rgba(traits.userInterfaceStyle == .dark ? dark : light)
        })
    }

    private static func rgba(_ value: UInt32) -> UIColor {
        UIColor(
            red: CGFloat((value >> 16) & 0xFF) / 255,
            green: CGFloat((value >> 8) & 0xFF) / 255,
            blue: CGFloat(value & 0xFF) / 255,
            alpha: CGFloat((value >> 24) & 0xFF) / 255
        )
    }
}

enum MobileDesignTypography {
    static let displayLarge = MobileTypographyToken(size: 24, lineHeight: 30, weight: .bold, textStyle: .largeTitle)
    static let displayMedium = MobileTypographyToken(size: 22, lineHeight: 28, weight: .bold, textStyle: .title1)
    static let displaySmall = MobileTypographyToken(size: 20, lineHeight: 26, weight: .bold, textStyle: .title2)
    static let headlineLarge = MobileTypographyToken(size: 22, lineHeight: 28, weight: .bold, textStyle: .title1)
    static let headlineMedium = MobileTypographyToken(size: 20, lineHeight: 26, weight: .bold, textStyle: .title2)
    static let headlineSmall = MobileTypographyToken(size: 18, lineHeight: 24, weight: .bold, textStyle: .title3)
    static let titleLarge = MobileTypographyToken(size: 20, lineHeight: 26, weight: .bold, textStyle: .title2)
    static let conversationHeaderTitle = MobileTypographyToken(size: 17, lineHeight: 22, weight: .medium, textStyle: .headline)
    static let titleMedium = MobileTypographyToken(size: 17, lineHeight: 22, weight: .medium, textStyle: .headline)
    static let titleSmall = MobileTypographyToken(size: 15, lineHeight: 20, weight: .medium, textStyle: .subheadline)
    static let bodyLarge = MobileTypographyToken(size: 16, lineHeight: 24, weight: .regular, textStyle: .body)
    static let bodyMedium = MobileTypographyToken(size: 14, lineHeight: 21, weight: .regular, textStyle: .callout)
    static let bodySmall = MobileTypographyToken(size: 13, lineHeight: 19, weight: .regular, textStyle: .footnote)
    static let labelLarge = MobileTypographyToken(size: 15, lineHeight: 20, weight: .medium, textStyle: .subheadline)
    static let labelMedium = MobileTypographyToken(size: 14, lineHeight: 18, weight: .medium, textStyle: .footnote)
    static let labelSmall = MobileTypographyToken(size: 12, lineHeight: 16, weight: .regular, textStyle: .caption1)
    static let brandWordmark = MobileTypographyToken(size: 42, lineHeight: 56, weight: .medium, textStyle: .largeTitle)
}

enum MobileDesignGeometry {
    static let conversationHeaderHeight: CGFloat = 76
    static let conversationHeaderCompactHeight: CGFloat = 64
    static let controlTouchSize: CGFloat = 48
    static let contentGutter: CGFloat = 16
    static let connectionStripHeight: CGFloat = 48
    static let timelineTopPadding: CGFloat = 22
    static let conversationOverlaySideInset: CGFloat = 16
    static let conversationEdgeFadeHeight: CGFloat = 28
    static let messageSpacing: CGFloat = 18
    static let messageBubbleMaxWidth: CGFloat = 276
    static let messageBubbleHorizontalPadding: CGFloat = 14
    static let messageBubbleVerticalPadding: CGFloat = 11
    static let messageBubbleRadius: CGFloat = 17
    static let composerActionSize: CGFloat = 48
    static let composerInputHeight: CGFloat = 44
    static let composerExpandedInputHeight: CGFloat = 58
    static let composerCollapsedHeight: CGFloat = 56
    static let composerExpandedInputRowHeight: CGFloat = 60
    static let composerExpandedActionRowHeight: CGFloat = 48
    static let composerExpandedHeight: CGFloat = 120
    static let composerCollapsedRadius: CGFloat = 28
    static let composerExpandedRadius: CGFloat = 18
    static let composerModelSelectorWidth: CGFloat = 330
    static let composerModelSelectorRadius: CGFloat = 14
    static let composerModelSelectorRowHeight: CGFloat = 48
    static let composerModelSelectorRowRadius: CGFloat = 9
    static let composerModelSelectorRowGap: CGFloat = 6
    static let sheetTopRadius: CGFloat = 28
    static let loginSheetMaxWidth: CGFloat = 560
    static let loginSheetOuterMargin: CGFloat = 8
    static let loginSheetBodyMinHeight: CGFloat = 142
    static let sheetSideRadius: CGFloat = 28
    static let sheetHorizontalPadding: CGFloat = 20
    static let sheetHeaderHeight: CGFloat = 56
    static let sheetActionHeight: CGFloat = 48
    static let selectionTopRadius: CGFloat = 20
    static let selectionRowHeight: CGFloat = 64
    static let selectionCloseSize: CGFloat = 48
    static let popoverWidth: CGFloat = 292
    static let popoverRadius: CGFloat = 16
    static let popoverPadding: CGFloat = 12
    static let popoverVerticalPadding: CGFloat = 10
    static let popoverActionHeight: CGFloat = 48
    static let popoverShadowRadius: CGFloat = 18
    static let compactPopoverWidth: CGFloat = 150
    static let compactPopoverRadius: CGFloat = 14
    static let compactPopoverActionHeight: CGFloat = 42
    static let settingsCompactCardRadius: CGFloat = 12
    static let settingsCardRadius: CGFloat = 16
    static let settingsProminentCardRadius: CGFloat = 20
    static let modelCurrentRowHeight: CGFloat = 64
    static let modelSourceRowHeight: CGFloat = 62
    static let modelAccountRowHeight: CGFloat = 56
    static let modelAccountRowGap: CGFloat = 6
    static let modelSectionGap: CGFloat = 20
    static let modelOverviewTopPadding: CGFloat = 16
    static let modelOverviewBottomPadding: CGFloat = 24
    static let modelListTopPadding: CGFloat = 10
    static let modelListBottomPadding: CGFloat = 16
    static let modelEmptyAccountHeight: CGFloat = 80
    static let modelEditorHeight: CGFloat = 560
    static let welcomeMaxWidth: CGFloat = 520
    static let welcomeGutter: CGFloat = 25
    static let welcomeHeaderHeight: CGFloat = 58
    static let welcomeButtonHeight: CGFloat = 49
    static let welcomeButtonGap: CGFloat = 11
    static let welcomeDockRadius: CGFloat = 30
    static let welcomeDockBottom: CGFloat = 39
    static let welcomeMarkSize: CGFloat = 92
    static let welcomeWordSize: CGFloat = 34
    static let welcomeStageHeight: CGFloat = 220
    static let welcomeHeaderWordSize: CGFloat = 17
    static let recentHomeGutter: CGFloat = 24
    static let recentHomeMarkSize: CGFloat = 132
    static let recentHomeTitleSize: CGFloat = 25
    static let recentHomeMaxWidth: CGFloat = 560
    static let recentHomeRowPadding: CGFloat = 18
    static let approvalCardRadius: CGFloat = 12
    static let approvalCardPadding: CGFloat = 12
    static let approvalCardGap: CGFloat = 8
    static let approvalActionRadius: CGFloat = 8
    static let approvalActionHeight: CGFloat = 36
}

enum MobileDesignBreakpoints {
    static let wide: CGFloat = 600
    static let extraWide: CGFloat = 840
    static let xl: CGFloat = 1440
}

enum MobileDesignMotion {
    static let quick: CGFloat = 180
    static let structure: CGFloat = 220
    static let startupBrand: CGFloat = 6800
    static let coldStartHome: CGFloat = 2400
}
