import type { ComponentMeta } from "../../registry.types";

export const askUserMeta = {
  category: "flow-chat",
  description: "A controlled question card with step navigation, shared selection controls, and custom answers that becomes a question-and-answer message after submission.",
  maturity: "stable",
  name: "AskUser",
  props: [
    { name: "questions", type: "readonly AskUserQuestion[]" },
    { defaultValue: "{}", name: "answers", type: "AskUserAnswers" },
    { defaultValue: "asking", name: "state", type: "AskUserState" },
    { name: "navigation", type: "AskUserNavigation" },
    { name: "disclosure", type: "{ label: ReactNode; collapseLabel: string; skipped?: boolean }" },
    { name: "summaryLabel", type: "ReactNode" },
    { name: "summaryDetail", type: "ReactNode" },
    { defaultValue: "false", name: "expanded", type: "boolean" },
    { name: "onAnswersChange", type: "(questionId, values) => void" },
    { name: "onSubmit", type: "() => void" },
  ],
  states: [
    "asking",
    "selected",
    "submitting",
    "submitted",
    "completed",
    "loading",
    "error",
    "disabled",
  ],
  tokens: [
    "color.action.neutral.content",
    "color.action.neutral.surfaceHover",
    "color.action.quiet.hover",
    "color.border.default",
    "color.border.subtle",
    "color.content.disabled",
    "color.content.inverse",
    "color.content.muted",
    "color.content.primary",
    "color.content.secondary",
    "color.focus.ring",
    "color.status.danger.border",
    "color.status.danger.content",
    "color.status.danger.surface",
    "color.status.success.content",
    "color.status.warning.border",
    "color.status.warning.content",
    "color.status.warning.surface",
    "color.surface.panel",
    "color.surface.subtle",
    "control.askUser.bodyGap",
    "control.askUser.bodyPadding",
    "control.activityItem.surfaceHeight",
    "control.activityItem.surfacePaddingBlock",
    "control.flowChat.cardPaddingInline",
    "control.flowChat.userMessageMaxWidth",
    "control.flowChat.userMessagePaddingBlock",
    "control.flowChat.userMessageRadius",
    "type.flow.control.fontFamily",
    "type.flow.control.fontSize",
    "type.flow.control.fontWeight",
    "type.flow.body.lineHeight",
    "type.flow.meta.fontFamily",
    "type.flow.meta.fontSize",
    "type.flow.meta.fontWeight",
    "type.flow.meta.lineHeight",
    "type.body.sm.lineHeight",
    "control.askUser.descriptionMaxWidth",
    "control.icon.sizeMd",
    "control.askUser.optionContentGap",
    "control.askUser.optionGap",
    "control.askUser.optionPaddingBlock",
    "control.askUser.optionPaddingInline",
    "control.askUser.questionOptionsGap",
    "control.askUser.summaryActionSize",
    "control.askUser.summaryPaddingBlock",
    "control.askUser.summaryPaddingInlineEnd",
    "control.askUser.summaryPaddingInlineStart",
    "control.hitTarget",
    "type.code.sm.fontFamily",
    "font.family.control",
    "font.size.sm",
    "font.size.xs",
    "font.weight.medium",
    "font.weight.regular",
    "font.weight.semibold",
    "lineHeight.base",
    "lineHeight.tight",
    "radius.base",
    "radius.lg",
    "radius.xs",
  ],
} as const satisfies ComponentMeta;
