import type { ComponentMeta } from "../../registry.types";

export const ambientToolCardMeta = {
  category: "flow-chat",
  description: "A low-attention tool trace that stays glanceable in the conversation and can reveal supporting detail.",
  maturity: "stable",
  name: "AmbientToolCard",
  props: [
    { name: "status", type: "FlowChatToolStatus" },
    { name: "header", type: "ReactNode" },
    { defaultValue: "false", name: "isExpanded", type: "boolean" },
    { defaultValue: "false", name: "requiresConfirmation", type: "boolean" },
    { name: "expandedContent", type: "ReactNode" },
    { defaultValue: "inset", name: "expandedContentLayout", type: "'inset' | 'flush'" },
    { name: "onClick", type: "() => void" },
  ],
  states: ["default", "hover", "loading", "expanded", "error", "confirmation"],
  tokens: [
    "control.flowChat.cardPaddingInline",
    "color.content.primary",
    "color.content.secondary",
    "color.content.muted",
    "color.surface.tertiary",
    "color.action.neutral.surface",
    "color.status.danger.content",
    "color.status.warning.emphasis",
    "control.height.md",
    "control.toolCard.ambientRowMinBlockSize",
    "control.flowChat.rowIconSize",
    "control.flowChat.rowIconGap",
    "font.family.sans",
    "font.size.sm",
    "font.size.xl",
    "font.weight.medium",
    "font.weight.regular",
    "radius.md",
    "radius.sm",
    "shadow.xs",
  ],
} as const satisfies ComponentMeta;
