import type { ComponentMeta } from "../../registry.types";

export const commandToolCardMeta = {
  category: "flow-chat",
  description: "A FlowChat command card with ambient or prominent presentation, a continuous expanded command/output surface, result status, metadata, and capability-driven actions.",
  maturity: "stable",
  name: "CommandToolCard",
  props: [
    { name: "status", type: "FlowChatToolStatus" },
    { name: "action", type: "ReactNode" },
    { defaultValue: "prominent", name: "attention", type: "ambient | prominent" },
    { name: "command", type: "string | null" },
    { name: "interaction", type: "ToolCardInteraction" },
    { name: "isExpanded", type: "boolean" },
    { name: "output", type: "ReactNode" },
    { defaultValue: "fixed", name: "outputSizing", type: "content | fixed" },
    { defaultValue: "false", name: "reserveOutput", type: "boolean" },
    { defaultValue: "false", name: "reserveFooter", type: "boolean" },
    { name: "footerItems", type: "readonly CommandToolCardFooterItem[]" },
    { name: "copyAction", type: "CommandToolCardCopyAction" },
    { name: "statusLabel", type: "ReactNode" },
    { defaultValue: "neutral", name: "statusTone", type: "danger | neutral | success | warning" },
  ],
  states: ["default", "hover", "loading", "expanded", "error", "confirmation"],
  tokens: [
    "control.flowChat.cardPaddingInline",
    "color.action.neutral.surface",
    "color.border.subtle",
    "color.content.primary",
    "color.content.secondary",
    "color.content.muted",
    "color.status.danger.content",
    "color.status.success.content",
    "color.status.success.emphasis",
    "color.status.warning.content",
    "color.surface.canvas",
    "color.surface.raised",
    "font.family.sans",
    "font.size.sm",
    "font.weight.regular",
    "radius.sm",
    "radius.lg",
    "type.flow.code.fontFamily",
    "type.flow.code.fontSize",
  ],
} as const satisfies ComponentMeta;
