import type { ComponentMeta } from "../../registry.types";

export const prominentToolCardMeta = {
  category: "flow-chat",
  description: "An attention-worthy tool result with a stable summary region, hover-revealed actions, and controlled detail disclosure.",
  maturity: "stable",
  name: "ProminentToolCard",
  props: [
    { name: "status", type: "FlowChatToolStatus" },
    { name: "summary", type: "ReactNode" },
    { defaultValue: "false", name: "isExpanded", type: "boolean" },
    { name: "expandedContent", type: "ReactNode" },
    { defaultValue: "inset", name: "expandedContentLayout", type: "'inset' | 'flush'" },
    { name: "errorContent", type: "ReactNode" },
    { defaultValue: "false", name: "allowExpandedWhenFailed", type: "boolean" },
    { defaultValue: "false", name: "requiresConfirmation", type: "boolean" },
  ],
  states: ["default", "hover", "loading", "expanded", "error", "confirmation"],
  tokens: [
    "control.flowChat.cardPaddingInline",
    "color.action.neutral.surface",
    "color.content.primary",
    "color.content.secondary",
    "color.content.muted",
    "color.surface.panel",
    "color.border.default",
    "color.border.strong",
    "color.border.subtle",
    "color.focus.ring",
    "color.status.danger.content",
    "color.status.success.content",
    "color.status.warning.border",
    "color.status.warning.surface",
    "control.height.sm",
    "font.family.sans",
    "font.size.base",
    "font.size.base",
    "font.size.lg",
    "font.size.sm",
    "font.size.xl",
    "font.weight.regular",
    "font.weight.semibold",
    "radius.md",
    "radius.sm",
    "shadow.xs",
    "shadow.sm",
  ],
} as const satisfies ComponentMeta;
